### DISCUSSION TITLE
Healthchecks.io Integration

### DISCUSSION THREAD

**Discussion by mark-monteiro** [tiredofit/docker-db-backup#159] [Q&A]
Thought I'd share the configuration I'm using to integrate with healthchecks.io using the support for custom pre and post scripts.

You end up with a log of backups run, with a duration for each backup, and can set up notifications for when a backup fails to run at the expected time, or does not completed within the expected amount of time.

![image](https://user-images.githubusercontent.com/2626103/190207230-208a8ad5-d88c-4078-879b-16867f1e2b41.png)

The scripts required and included below. You can re-use these scripts between multiple container instances, you just need to set a different `HEALTHCHECK_URL` environment variable value for each container.

Below is an example of the relevant parts you would need to add to a Docker Compose file (be sure to update `HEALTHCHECK_URL`)

```yml
  postgres-backup:
    image: tiredofit/db-backup:3.4.1
    volumes:
      - ./pre-script.sh:/assets/scripts/pre/pre-script.sh:ro
      - ./post-script.sh:/assets/scripts/post/post-script.sh:ro
    environment:
      - HEALTHCHECK_URL=https://hc-ping.com/00000000-0000-0000-0000-000000000000
```

## Pre Script
```sh
#!/bin/sh

# Define command output to send to Healthchecks.io
# See: https://github.com/tiredofit/docker-db-backup#pre-backup
m=$(echo "'${1}' backup started on host '${2}' for db '${3}'. Filename: ${5}")

# Send update to healthchecks.io
# See: https://healthchecks.io/docs/measuring_script_run_time/
curl -fsS -m 30 --retry 5 --data-raw "$m" ${HEALTHCHECK_URL}/start
```

## Post Script
```sh
#!/bin/sh

# Define command output to send to Healthchecks.io
# See: https://github.com/tiredofit/docker-db-backup#post-backup
m=$(echo "'${2}' backup completed on host '${3}' for db '${4}' after ${7} seconds. Filename: ${8} Size: ${9} MD5: ${10}")

# Send update to healthchecks.io
# See: https://healthchecks.io/docs/bash/
curl -fsS -m 30 --retry 5 --data-raw "$m" ${HEALTHCHECK_URL}/${1}
```
