### DISCUSSION TITLE
Dump all postgres databases?

### DISCUSSION THREAD

**Discussion by Magneticdud** [tiredofit/docker-db-backup#379] [Q&A]
my compose configuration:

```
postgres15:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: mydb
backup:
    restart: unless-stopped
    depends_on:
      - postgres15
    image: tiredofit/db-backup
    volumes:
      - /mnt/Backups/:/backup
    environment:
      - USER_DBBACKUP=1001
      - GROUP_DBBACKUP=1001
      - DEFAULT_BACKUP_BEGIN=0328
      - DEFAULT_CLEANUP_TIME=43200
      - DB01_TYPE=pgsql
      - DB01_HOST=postgres15
      - DB01_USER=pguser
      - DB01_PASS=pgpass
      - DB01_NAME=ALL
      - CONTAINER_ENABLE_MONITORING=FALSE
```

i get this error and no backup is produced:

psql: error: connection to server at "postgres15" (172.27.0.5), port 5432 failed: FATAL:  database "pguser" does not exist

how could i fix this? I'd like to dump all, not only the mydb database

In another instance where everything has the same value (user, pass and dbname is all set to pgsql), DB01_NAME=ALL works as expected, making separate exports
