### DISCUSSION TITLE
Influx backups are . . . not

### DISCUSSION THREAD

**Discussion by DowlingIT** [tiredofit/docker-db-backup#394] [Q&A]
I have in influx 2 db that I'm trying to back up.  As far as I can tell, everything is setup as it should be.  The logs indicate it tries, but there are no errors shown, but also no backup files generated.  I can confirm that data is present in the database.

My config is below.  The influx db is DB04.

```
services:
  db-backup:
    hostname: db-backup
    container_name: db-backup
    image: tiredofit/db-backup
    user: ${PUID}:${PGID}
    volumes:
      - /mnt/nasbackups/dbbackups/:/backup
      - ${DOCKERDIR}/includes/db-backup/post-script.sh:/assets/custom-scripts/post-script.sh
      - ${DOCKERDIR}/logs/$HOSTNAME/db-backup:/logs
      #source sqllite dbs
      - $DOCKERDIR/appdata/frigate/config/:/mnt/frigate
      - $DOCKERDIR/appdata/crowdsec/data/:/mnt/crowdsec
      - $DOCKERDIR/appdata/home-assistant/:/mnt/home-assistant
      - $DOCKERDIR/appdata/uptime-kuma/:/mnt/uptime-kuma
    restart: unless-stopped
    networks:
      - app_proxy
      - authentik-backend
      - app_backend
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    secrets:
      - authentik_postgresql_db
      - authentik_postgresql_user
      - authentik_postgresql_password
    environment:
      - TIMEZONE=$TZ
      - CONTAINER_NAME=db-backup
      - CONTAINER_ENABLE_MONITORING=FALSE
      - USER_DBBACKUP=$PUID
      - GROUP_DBBACKUP=$PGID
      - DEBUG_MODE=FALSE

      - BACKUP_JOB_CONCURRENCY=1     # Only run one job at a time
      - DEFAULT_CHECKSUM=NONE        # Don't create checksums
      - DEFAULT_COMPRESSION=ZSTD     # Compress all with ZSTD
      - DEFAULT_BACKUP_INTERVAL=1440   # Backup every 1440 minutes
      - DEFAULT_BACKUP_BEGIN=0030      # Start backing up at midnight thirty
      - DEFAULT_CLEANUP_TIME=8640    # Cleanup backups after a week

      - DB01_TYPE=postgres
      - DB01_HOST=authentik_postgresql
      - DB01_NAME_FILE=$POSTGRES_DB_FILE
      - DB01_USER_FILE=$POSTGRES_USER_FILE
      - DB01_PASS_FILE=$POSTGRES_PASSWORD_FILE

      - DB02_TYPE=redis
      - DB02_HOST=authentik_redis
      - DB02_BACKUP_BEGIN=0045

      - DB03_TYPE=redis
      - DB03_HOST=redis
      - DB03_PASS=$REDIS_PASSWORD
      - DB03_BACKUP_BEGIN=0100

      - DB04_TYPE=influx
      - DB04_HOST=influxdb
      - DB04_USER=$INFLUX_USER
      - DB04_PASS=$INFLUX_PASSWORD
      - DB04_INFLUX_VERSION=2
      - DB04_BACKUP_BEGIN=0115
      
      - DB05_TYPE=sqlite3
      - DB05_HOST=/mnt/frigate/frigate.db
      - DB05_BACKUP_BEGIN=0130

      - DB06_TYPE=sqlite3
      - DB06_HOST=/mnt/crowdsec/crowdsec.db   
      - DB06_BACKUP_BEGIN=0145
      
      - DB07_TYPE=sqlite3
      - DB07_HOST=/mnt/home-assistant/home-assistant_v2.db   
      - DB07_BACKUP_BEGIN=0200
      
      - DB08_TYPE=sqlite3
      - DB08_HOST=/mnt/uptime-kuma/kuma.db   
      - DB08_BACKUP_BEGIN=0215
```

The logs appear to show that the influx backup worked:
![image](https://github.com/user-attachments/assets/c8717e99-b76e-44d1-b2df-e235f972123f)

However, the influx backup is not present, where other backups all worked as expected:
![image](https://github.com/user-attachments/assets/c9a4a1f1-5dfd-4459-9ce4-13079edfe392)

When comparing to logs for other backups that did work, the influx logs appear to be missing some steps (though no idea what).  Postgres logs, for example:
![image](https://github.com/user-attachments/assets/8dde2463-479b-4759-a328-2160e5b007ac)

Influx is version 2.  
```
services:
  influxdb:
    hostname: influxdb
    container_name: influxdb
    image: influxdb:2
    user: ${PUID}:${PGID}
    networks:
      - app_proxy
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/appdata/influxdb2:/var/lib/influxdb2
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.influxdb-rtr.rule=Host(`influxdb.${DOMAINNAME_1}`)"
      - "traefik.http.routers.influxdb-rtr.entrypoints=websecure"
      ## Middlewares
      - "traefik.http.routers.influxdb-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.influxdb-rtr.service=influxdb-svc"
      - "traefik.http.services.influxdb-svc.loadBalancer.server.port=8086"
```

I can log into the influx UI by copy/pasting credentials used in the backup compose, and view graphs, data, etc.

So I have no idea what next steps to take on getting the influx backup to work.  I've reviewed the documentation for any environment variables I am mis-using or missing.  I do not see in the discussions where anyone else is having issues similar to this.
