### DISCUSSION TITLE
Backup multiple databases at the same time

### DISCUSSION THREAD

**Discussion by yeranosyanvahan** [tiredofit/docker-db-backup#97] [Q&A]
Hello everyone and Happy New Year.
I am curious what is the best way to backup multiple different databases. 

```
version: '3'
services:
 mariadb:
  image: mariadb:10.6
.......
 postgres:
  image: postgres
.......
 backup:
  image: tiredofit/db-backup
......
```
