### ISSUE TITLE
[Bug] Docker secrets not working

### ISSUE THREAD

**Issue by tpansino** [tiredofit/docker-db-backup#115]
### Summary

I use Docker secrets to mount my database passwords, and the current release (v3.2.1) is not working with them. I'm getting a password prompt, both for MariaDB 10 and Postgres 14. Passing the password as an env var is working as a workaround.

### Steps to reproduce

1. Create a `docker-compose.yml` similar to the following:
```
version: '3.7'

services:
  db:
    image: postgres:14
    restart: on-failure:5
    volumes:
      - /srv/test/db:/var/lib/postgresql/data
    secrets:
      - POSTGRES_PASSWORD
    environment:
      POSTGRES_PASSWORD_FILE: "/run/secrets/POSTGRES_PASSWORD"
      POSTGRES_USER: "test"
      POSTGRES_DB: "test"
    networks:
      - backend

  backup:
    image: tiredofit/db-backup:latest
    restart: on-failure:5
    volumes:
      - /srv/test/backups:/backup
    secrets:
      - POSTGRES_PASSWORD
    environment:
      COMPRESSION: "xz"
      DB_TYPE: "pgsql"
      DB_HOST: "db"
      DB_NAME: "test"
      DB_USER: "test"
      DB_PASS_FILE: "/run/secrets/POSTGRES_PASSWORD"
      DB_DUMP_BEGIN: "0001"
      DB_CLEANUP_TIME: "14400"  # 14400 min = 10 days
      ENABLE_CHECKSUM: "false"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

secrets:
  POSTGRES_PASSWORD:
    file: /srv/test/POSTGRES_PASSWORD.txt
```
2. Run `cat mypassword > /srv/test/POSTGRES_PASSWORD.txt` to give the DB a password
3. Run `docker-compose up -d` to bring everything online
4. Run `docker-compose exec backup backup-now` and get prompted to enter a password

### What is the expected *correct* behavior?

Backup should be created.

### Relevant logs and/or screenshots

```
** Performing Manual Backup
2022-04-11.02:38:52 [DEBUG] ** [db-backup] Looking for existence of DB_NAME environment variable
2022-04-11.02:38:52 [DEBUG] ** [db-backup] Detected Manual Mode
2022-04-11.02:38:52 [DEBUG] ** [db-backup] Backup routines started time: 2022-04-11 02:38:52 GMT
2022-04-11.02:38:52 [DEBUG] ** [db-backup] Databases Found: test
2022-04-11.02:38:52 [NOTICE] ** [db-backup] Dumping PostgresSQL database: 'test' and compressing with 'xzip:3' with '16' threads
Password:
```
(prompt for password causes the container to hang)

### Environment

- Image version / tag:  Docker image v3.2.1
- Host OS: Ubuntu 20.04
    
### Possible fixes

Seems similar to #46 (which was also a report I made 😄). The code has moved around since then, but the changes I made in #47 to fix it are still intact, so I don't think it's the same root cause.

I'm thinking it might be a result of changes for v3, but haven't had the time to deep dive yet.
