### ISSUE TITLE
Error backing up Postgres DB w/out password.

### ISSUE THREAD

**Issue by CorneliousJD** [tiredofit/docker-db-backup#116]
### Summary

Using docker-compose with the following config, I cannot backup a pgsql database w/out a pass, as the error in the logs shows
2022-04-13.14:06:46 [ERROR] ** [db-backup] error: neither DB_PASS nor DB_PASS_FILE are set but are required
Yet the documentation does say that DB_PASS is optional if the DB doesn't require a pass.

If I run it like this and do sudo docker exec backups run-now it DOES work and backs up the file though.
Weird...

### Steps to reproduce

docker-compose.yml with a postgres DB to backup w/out a password.

### What is the expected *correct* behavior?

It should not error on DB_PASS not being present as it's optional. 

### Relevant logs and/or screenshots

`[ERROR] ** [db-backup] error: neither DB_PASS nor DB_PASS_FILE are set but are required
`
### Environment

- Image version / tag:  latest
- Host OS: Ubuntu Server 20.02 LTS

```
backups:
    image: tiredofit/db-backup
    volumes:
      - /home/xxx/backup:/backup
    restart: unless-stopped
    links:
      - db
    environment:
      DB_TYPE: 'pgsql'
      DB_HOST: 'db'
      DB_NAME: 'xxx_production'
      DB_USER: 'postgres'
      COMPRESSION: 'GZ'
      DB_DUMP_FREQ: '1440'
      DB_DUMP_BEGIN: '2200'
      DB_CLEANUP_TIME: '10080'
```

    
### Possible fixes
Remove check for DB_PASS for scheduled runs if it's optional?
