### ISSUE TITLE
Backups falling to move/rename.

### ISSUE THREAD

**Issue by CorneliousJD** [tiredofit/docker-db-backup#122]
### Summary

Testing a backup with a backup-now command results in the error

```
2022-04-24.19:23:06 [DEBUG] ** [db-backup] Moving backup to filesystem
mv: can't rename '/tmp/backups/*.': No such file or directory
```

Note, I have also tried providing a separate temp directory for it to work on in my host file system, but that still fails.

### Steps to reproduce

Updated to :latest to fix issue w/ Postgres backup w/ no pass provided and now this issue has started occuring.

### What is the expected *correct* behavior?

It should create the bakckup and move it.

### Relevant logs and/or screenshots

```
sudo docker exec backups backup-now
** Performing Manual Backup
2022-04-24.19:16:36 [DEBUG] ** [db-backup] Looking for existence of DB_NAME environment variable
2022-04-24.19:16:36 [DEBUG] ** [db-backup] Detected Manual Mode
2022-04-24.19:16:36 [DEBUG] ** [db-backup] Backup routines started time: 2022-04-24 19:16:36 EDT
2022-04-24.19:16:36 [DEBUG] ** [db-backup] Databases Found: xxx_production
2022-04-24.19:16:36 [NOTICE] ** [db-backup] Dumping PostgresSQL database: 'xxx_production' and compressing with 'gzip:3' with '2' threads

2022-04-24.19:16:49 [DEBUG] ** [db-backup] DB Backup Exit Code is 0
2022-04-24.19:16:49 [INFO] ** [db-backup] DB Backup of 'pgsql_xxx_production_db_20220424-191636.sql.gz' completed successfully
2022-04-24.19:16:49 [NOTICE] ** [db-backup] Backup of pgsql_xxx_production_db_20220424-191636.sql.gz created with the size of 99013616 bytes
2022-04-24.19:16:49 [DEBUG] ** [db-backup] Moving backup to filesystem
mv: can't rename '/tmp/backups/*.': No such file or directory
2022-04-24.19:16:49 [NOTICE] ** [db-backup] Sending Backup Statistics to Zabbix
Sending failed. Use option -vv for more detailed output.
Sending failed. Use option -vv for more detailed output.
Sending failed. Use option -vv for more detailed output.
Sending failed. Use option -vv for more detailed output.
2022-04-24.19:17:09 [NOTICE] ** [db-backup] Found POST_SCRIPT environment variable. Executing '/scripts/backup_complete.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     2  100     2    0     0      4      0 --:--:-- --:--:-- --:--:--     4
OK2022-04-24.19:17:09 [NOTICE] ** [db-backup] DB Backup for 'xxx_production' time taken: Hours: 0 Minutes: 00 Seconds: 13
2022-04-24.19:17:09 [INFO] ** [db-backup] Backup routines finish time: 2022-04-24 19:17:09 EDT with overall exit code 0
2022-04-24.19:17:09 [NOTICE] ** [db-backup] Backup routines time taken: Hours: 0 Minutes: 00 Seconds: 33
2022-04-24.19:17:09 [INFO] ** [db-backup] Cleaning up old backups
2022-04-24.19:17:10 [DEBUG] ** [db-backup] Exiting due to manual mode
```

### Environment
```
  backups:
    image: tiredofit/db-backup
    container_name: backups
    volumes:
      - /home/xxx/yyy/backups:/backup
      - /home/xxx/yyy/scripts:/scripts
    restart: unless-stopped
    links:
      - db
    environment:
      TZ: 'America/Detroit'
      DB_TYPE: 'pgsql'
      DB_HOST: 'db'
      DB_NAME: 'xxx_production'
      DB_USER: 'postgres'
      EXTRA_OPTS: '--schema=public --blobs'
      COMPRESSION: 'GZ'
      ENABLE_CHECKSUM: 'FALSE'
      DB_DUMP_FREQ: '360'
      DB_DUMP_BEGIN: '+10'
      DB_CLEANUP_TIME: '10080'
      POST_SCRIPT: '/scripts/backup_complete.sh'
```

- Image version / tag:  tiredofit/db-backup:latest
- Host OS: Ubuntu Server 20.04.4 LTS

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>
