### ISSUE TITLE
mongodump: illegal argument combination: cannot specify --username and --uri

### ISSUE THREAD

**Issue by dumbasPL** [tiredofit/docker-db-backup#161]
### Summary

Mongo db backup broke

### Steps to reproduce

1. run the docker-compose from #Environment
2. observe error
```
error parsing command line options: illegal argument combination: cannot specify --username and --uri
try 'mongodump --help' for more information
```

### What is the expected *correct* behavior?

`DB Backup of 'mongo_test_mongo_20220929-114619.archive.gz' completed successfully`

### Relevant logs and/or screenshots

```
tmpnvdkfyvuf8-mongo-backup-1  |                                                                        ,---.
tmpnvdkfyvuf8-mongo-backup-1  | ,--------.,--.                 ,--.            ,---.    ,--. ,--------.|   |
tmpnvdkfyvuf8-mongo-backup-1  | '--.  .--'`--',--.--. ,---.  ,-|  |     ,---. /  .-'    |  | '--.  .--'|  .'
tmpnvdkfyvuf8-mongo-backup-1  |    |  |   ,--.|  .--'| .-. :' .-. |    | .-. ||  `-,    |  |    |  |   |  |
tmpnvdkfyvuf8-mongo-backup-1  |    |  |   |  ||  |   \   --.\ `-' |    ' '-' '|  .-'    |  |.--.|  |   `--'
tmpnvdkfyvuf8-mongo-backup-1  |    `--'   `--'`--'    `----' `---'      `---' `--'      `--''--'`--'   .--.
tmpnvdkfyvuf8-mongo-backup-1  |                                                                        '--'
tmpnvdkfyvuf8-mongo-backup-1  | Image:  tiredofit/db-backup | Version  3.4.0 Type 'image_changelog' for details
tmpnvdkfyvuf8-mongo-backup-1  | Repository/Issues/Support:  https://github.com/tiredofit/docker-db-backup/
tmpnvdkfyvuf8-mongo-backup-1  |            Sponsor me for development and upkeep: https://www.tiredofit.ca/sponsor
tmpnvdkfyvuf8-mongo-backup-1  | 
tmpnvdkfyvuf8-mongo-backup-1  | 2022-09-29.11:49:47 [NOTICE] ** [scheduling] Container configured for scheduled tasks with 'cron'
tmpnvdkfyvuf8-mongo-backup-1  | 2022-09-29.11:49:47 [STARTING] ** [scheduling] [1] Starting cron
tmpnvdkfyvuf8-mongo-backup-1  | 2022-09-29.11:49:52 [INFO] ** [db-backup] Next Backup at 2022-09-29 11:49:52 GMT
tmpnvdkfyvuf8-mongo-backup-1  | 2022-09-29.11:49:52 [NOTICE] ** [db-backup] Dumping MongoDB database: 'test' and compressing with gzip
tmpnvdkfyvuf8-mongo-backup-1  | 2022-09-29T11:49:52.582+0000	error parsing command line options: illegal argument combination: cannot specify --username and --uri
tmpnvdkfyvuf8-mongo-backup-1  | 2022-09-29T11:49:52.582+0000	try 'mongodump --help' for more information
tmpnvdkfyvuf8-mongo-backup-1  | 2022-09-29.11:49:52 [ERROR] ** [db-backup] DB Backup of 'mongo_test_mongo_20220929-114952.archive.gz' reported errors
tmpnvdkfyvuf8-mongo-backup-1  | 2022-09-29.11:49:52 [ERROR] ** [db-backup] Skipping Checksum creation because backup did not complete successfully
tmpnvdkfyvuf8-mongo-backup-1  | 2022-09-29.11:49:52 [ERROR] ** [db-backup] Skipping moving DB Backup to final location because backup did not complete successfully
tmpnvdkfyvuf8-mongo-backup-1  | 2022-09-29.11:49:52 [NOTICE] ** [db-backup] DB Backup for '' time taken: Hours: 0 Minutes: 00 Seconds: 00
tmpnvdkfyvuf8-mongo-backup-1  | 2022-09-29.11:49:52 [INFO] ** [db-backup] Backup routines finish time: 2022-09-29 11:49:52 GMT with overall exit code 1
tmpnvdkfyvuf8-mongo-backup-1  | 2022-09-29.11:49:52 [NOTICE] ** [db-backup] Backup routines time taken: Hours: 0 Minutes: 00 Seconds: 00
tmpnvdkfyvuf8-mongo-backup-1  | 2022-09-29.11:49:52 [NOTICE] ** [db-backup] Sleeping for another 86400 seconds. Waking up at 2022-09-30 11:49:52 GMT
```

### Environment

- Image version / tag:  3.4.0-3.4.2 (3.3.12 works fine)
- Host OS: Debian 11 and Arch Linux

<details>
<summary>Any logs | docker-compose.yml</summary>

```yaml
version: '3.8'
services:
  mongo:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
  mongo-backup:
    image: tiredofit/db-backup:3.4.2
    restart: always
    volumes:
      - ./backup:/backup
    environment:
      # - DEBUG_MODE=true
      - CONTAINER_ENABLE_MONITORING=false
      - DB_AUTH=admin
      - DB_TYPE=mongo
      - DB_HOST=mongo
      - DB_NAME=test
      - DB_USER=root
      - DB_PASS=test
```

</details>

versions 3.4.0 and up are affected, below that works as expected
    
### Possible fixes
use the correct mongodump syntax for the new version
