### ISSUE TITLE
Failed MySQL backup with TLS connection

### ISSUE THREAD

**Issue by buxm** [tiredofit/docker-db-backup#192]
### Summary

Database backup fails when MySQL server requires TLS connection.

### Steps to reproduce

`docker compose -f docker-compose.db-backup-restore.yml run --rm db-backup-restore backup-now`
(See below for content of `docker-compose.db-backup-restore.yml`)
The output is:
`2022-12-11.21:07:34 [WARN] /etc/services.available/10-db-backup/run ** [db-backup] MySQL/MariaDB Server 'eu-central.connect.psdb.cloud' is not accessible, retrying.. (5 seconds so far)`

### What is the expected *correct* behavior?

The connection to a MySQL server requiring TLS connections is successful, provided that $EXTRA_OPTS contains the required options for TLS.

### Relevant logs and/or screenshots

The debug log shows at a certain point:
```
2022-12-11.21:07:34 [WARN] /etc/services.available/10-db-backup/run ** [db-backup] MySQL/MariaDB Server 'eu-central.connect.psdb.cloud' is not accessible, retrying.. (5 seconds so far)
+ mysqladmin -udbuser -P3306 -heu-central.connect.psdb.cloud status
+ sleep 5
```

### Environment

- Image version / tag: 3.6.1
- Host OS: Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1025-oracle aarch64)

<details>
<summary>docker-compose.db-backup-restore.yml</summary>

```
version: "3.5"
services:
  db-backup-restore:
    image: tiredofit/db-backup:latest
    
    volumes:
      - "./db_backup:/backup"
      - "./db_backup/tmp:/tmp/backups/"
      
    environment:
      - MODE=MANUAL
      - MANUAL_RUN_FOREVER=FALSE
      - CONTAINER_ENABLE_SCHEDULING=FALSE
      - BACKUP_LOCATION=S3

      - DB_TYPE=mysql
      - DB_HOST=eu-central.connect.psdb.cloud
      - DB_NAME=database
      - DB_USER=dbuser
      - DB_PASS=dbpassword
      - EXTRA_OPTS=--ssl-verify-server-cert=TRUE --ssl-ca=/etc/ssl/cert.pem
      
      - CHECKSUM=SHA1
      - SPLIT_DB=FALSE
      - COMPRESSION=XZ
      - COMPRESSION_LEVEL=9
      
      - S3_BUCKET=s3bucket
      - S3_KEY_ID=S3_key_id
      - S3_KEY_SECRET=S3_key_secret
      - S3_PATH=mysql
      - S3_REGION=s3region
      - S3_HOST=s3host
      - S3_CERT_SKIP_VERIFY=FALSE
      
      - CONTAINER_ENABLE_MONITORING=FALSE
      
      - DEBUG_MODE=true
```
</details>

    
### Possible fixes
If I attempt to run the same command from a shell in the container:
```
docker compose -f docker-compose.db-backup-restore.yml run --it db-backup-restore bash
export MYSQL_PWD=dbpassword
mysqladmin -udbuser -P3306 -heu-central.connect.psdb.cloud status
mysqladmin: connect to server at 'eu-central.connect.psdb.cloud' failed
error: 'unknown error: Code: UNAVAILABLE
server does not allow insecure connections, client must use SSL/TLS
```
So the connection fails because the mysqladmin command does not use the `$EXTRA_OPTS` variable that I set.
If I run again a similar command:
`mysqladmin -udbuser -P3306 -heu-central.connect.psdb.cloud $EXTRA_OPTS status`
The connection is successful.

So it is probably sufficient to amend the code of the backup script to add `$EXTRA_OPTS` to the `mysqladmin` command (and to any further mysql command that is executed anywhere else)
