### ISSUE TITLE
Cron: Invalid Date, fails to implement backup schedule

### ISSUE THREAD

**Issue by jluo98** [tiredofit/docker-db-backup#198]
### Summary

When starting container, logs show an error of invalid date from cron. Since cron implementation fails, container defaults to backup up immediately and then every 1440 minutes. 

### Steps to reproduce

Start with `docker compose up -d` using the `docker-compose.yml` below as part of traefik: 

````
db-backup:
  image: tiredofit/db-backup:latest
  volumes:
    - /root/backups/traefik/database:/backup
  environment:
    TZ: America/Chicago
    DB_TYPE: mariadb
    DB_HOST: mariadb
    DB_NAME: ALL
    DB_NAME_EXCLUDE: information_schema,mysql,performance_schema,sys
    DB_USER: root
    DB_PASS: ############
    DB_PORT: 3306
    DB_DUMP_FREQ: 240
    DB_DUMP_BEGIN: 0200
    DB_CLEANUP_TIME: 43200
    COMPRESSION: GZ
    CHECKSUM: SHA1
    CONTAINER_ENABLE_MONITORING: FALSE
  labels:
    - traefik.enable=false
  networks:
    - internal
  restart: always
````

### What is the expected *correct* behavior?

Implement the backup schedule indicated in the env variables. 

### Relevant logs and/or screenshots

````
Image:  tiredofit/db-backup | Version  3.7.3 Type 'image_changelog' for details
Repository/Issues/Support:  https://github.com/tiredofit/docker-db-backup/
           Sponsor me for development and upkeep: https://www.tiredofit.ca/sponsor
2022-12-29.22:55:40 [NOTICE] ** [scheduling] Container configured for scheduled tasks with 'cron'
2022-12-29.22:55:41 [STARTING] ** [scheduling] [1] Starting cron
date: invalid date '20221229128'
2022-12-29.22:55:46 [INFO] ** [db-backup] Next Backup at 1970-01-01 18:00:00 CST
sleep: invalid number '-1672289746'
````
(Backing up immediately)
````
2022-12-29.22:55:47 [INFO] ** [db-backup] Backup routines finish time: 2022-12-29 22:55:47 CST with overall exit code 0
2022-12-29.22:55:47 [NOTICE] ** [db-backup] Backup routines time taken: Hours: 0 Minutes: 00 Seconds: 01
2022-12-29.22:55:47 [INFO] ** [db-backup] Cleaning up old backups on filesystem
2022-12-29.22:55:47 [NOTICE] ** [db-backup] Sleeping for another 14399 seconds. Waking up at 2022-12-30 02:55:46 CST 
````

### Environment

- Image version / tag:  tiredofit/db-backup:3.7.3
- Host OS: Ubuntu Server 22.04 LTS

    
### Possible fixes

I'm assuming that there is an error taking in the `DB_DUMP_BEGIN` env variable, or the cron argument needs to be fixed for the schedule to work.

**Comment by alwynpan** [comment]
I did a little bit digging and found the issue is possibly from this:

`$ date --date="202301040200" +"%s" --debug
date: parsed number part: (Y-M-D) 20230104-02-00
date: input timezone: system default
date: warning: using midnight as starting time: 00:00:00
date: error: invalid date/time value:
date:     user provided time: '(Y-M-D) 20230104-02-00 00:00:00'
date:        normalized time: '(Y-M-D) 20230104-01-31 00:00:00'
date:                                       -- --
date:      possible reasons:
date:        invalid day/month combination;
date:        numeric values overflow;
date:        missing timezone
date: invalid date ‘202301040200’`

**Comment by tiredofit** [comment]
Try quoting your variables. There's a segment in the readme that talks about an edge case, this may be one of them..

**Comment by alwynpan** [comment]
Ignore my comment above, I tried this with Ubuntu Focal. The image is Alpine based. I have just tried to recreate the issue reported, but I wasn't able to. 

My `docker-compose.yaml`:

```
version: '2'

networks:
  example-db-network:
    name: example-db-network

services:
  example-db:
    hostname: example-db-host
    container_name: example-db
    image: mariadb:latest
    ports:
      - 13306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=examplerootpassword
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=examplepassword
    restart: always
    networks:
      - example-db-network

  example-db-backup:
    container_name: example-db-backup
    image: tiredofit/db-backup
    links:
     - example-db
    volumes:
      - ./backups:/backup
      #- ./post-script.sh:/assets/custom-scripts/post-script.sh
    environment:
      - TZ=America/Chicago
      # - DEBUG_MODE=TRUE
      - DB_TYPE=mariadb
      - DB_HOST=example-db-host
      - DB_NAME=ALL
      - DB_NAME_EXCLUDE=information_schema,mysql,performance_schema,sys
      - DB_USER=example
      - DB_PASS=examplepassword
      - DB_DUMP_FREQ=240            # backup every minute
      - DB_DUMP_BEGIN=0015      # backup starts immediately
      - DB_CLEANUP_TIME=5         # clean backups they are older than 5 minute
      - CHECKSUM=SHA1
      - COMPRESSION=GZ
      - SPLIT_DB=FALSE
      - CONTAINER_ENABLE_MONITORING=FALSE
    restart: always
    networks:
      - example-db-network
```

Output:

```
❯ docker logs -f example-db-backup
                                                                       ,---.
,--------.,--.                 ,--.            ,---.    ,--. ,--------.|   |
'--.  .--'`--',--.--. ,---.  ,-|  |     ,---. /  .-'    |  | '--.  .--'|  .'
   |  |   ,--.|  .--'| .-. :' .-. |    | .-. ||  `-,    |  |    |  |   |  |
   |  |   |  ||  |   \   --.\ `-' |    ' '-' '|  .-'    |  |.--.|  |   `--'
   `--'   `--'`--'    `----' `---'      `---' `--'      `--''--'`--'   .--.
                                                                       '--'
Image:  tiredofit/db-backup
Repository/Issues/Support:  https://github.com/tiredofit/docker-db-backup/
           Sponsor me for development and upkeep: https://www.tiredofit.ca/sponsor

2023-01-04.00:12:14 [NOTICE] ** [scheduling] Container configured for scheduled tasks with 'cron'
2023-01-04.00:12:14 [STARTING] ** [scheduling] [1] Starting cron
2023-01-04.00:12:19 [INFO] ** [db-backup] Next Backup at 2023-01-04 00:15:00 CST
2023-01-04.00:15:00 [NOTICE] ** [db-backup] Dumping all MySQL / MariaDB databases: 'example' and compressing with 'gzip'
2023-01-04.00:15:01 [INFO] ** [db-backup] DB Backup of 'mysql_all_example-db-host_20230104-001500.sql.gz' completed successfully
2023-01-04.00:15:01 [NOTICE] ** [db-backup] Generating SHA1 for 'mysql_all_example-db-host_20230104-001500.sql.gz'
2023-01-04.00:15:01 [NOTICE] ** [db-backup] Backup of mysql_all_example-db-host_20230104-001500.sql.gz created with the size of 588 bytes
2023-01-04.00:15:01 [NOTICE] ** [db-backup] DB Backup for 'all' time taken: Hours: 0 Minutes: 00 Seconds: 01
2023-01-04.00:15:01 [INFO] ** [db-backup] Backup routines finish time: 2023-01-04 00:15:01 CST with overall exit code 0
2023-01-04.00:15:01 [NOTICE] ** [db-backup] Backup routines time taken: Hours: 0 Minutes: 00 Seconds: 01
2023-01-04.00:15:01 [INFO] ** [db-backup] Cleaning up old backups on filesystem
2023-01-04.00:15:01 [NOTICE] ** [db-backup] Sleeping for another 14399 seconds. Waking up at 2023-01-04 04:15:00 CST 
```
