### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by AnderssonPeter** [tiredofit/docker-db-backup#2]
Hi i have the following `docker-compose`
```yaml
  mariadb_backup:
    image: tiredofit/db-backup
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./mariadb/backups:/backup
    links:
      - mariadb
    environment:
      - DB_TYPE=mariadb
      - DB_HOST=mariadb
      - DB_NAME=homeassistant
      - DB_USER=backup
      - DB_PASS="secret"
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=1700
      - DB_CLEANUP_TIME=8640
      - MD5=TRUE
      - COMPRESSION=XZ
      - SPLIT_DB=TRUE
```

But i can't get it to work, when it runs i get the following error:
```bash
** [db-backup] Dumping database: homeassistant,
./run: line 206: =xz: command not found,
mv: can't rename '/tmp/backups/mysql_homeassistant_mariadb_20181005-171600.sql.xz': No such file or directory,
```
it creates a md5 file but no actual backup file!
