### ISSUE TITLE
Maridb not working how to interpret these errors

### ISSUE THREAD

**Issue by djaffer** [tiredofit/docker-db-backup#201]
### Summary

I am using this for mariadb with version 10.9 and it seems that this is failing to do an backups.

### Relevant logs and/or screenshots
![image](https://user-images.githubusercontent.com/5740725/219576856-933023a5-a3cd-449b-aa97-644e40d679c6.png)

### Environment

- Image version / tag:  
- Host OS:

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>

 environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USERNAME}
      - DB_PASS=${DB_PASSWORD}
      - DB_TYPE=mysql
      - DB_DUMP_FREQ=15
      - DB_CLEANUP_TIME=120
      - MD5=TRUE
      - SPLIT_DB=FALSE
      - EXTRA_OPTS=--single-transaction
    restart: unless-stopped

**Comment by gbe0** [comment]
Hi,

Same issue for me; it is not related to the database type rather it is caused by the extra linebreak here: https://github.com/tiredofit/docker-db-backup/blob/main/install/assets/functions/10-db-backup#L834

I submitted a pull request to get that removed. In the mean time you can build the image without that extra space and it should resolve the problem for you.

**Comment by tiredofit** [comment]
Thanks, I'll get this merged asap.

**Comment by djaffer** [comment]
@tiredofit any update?

**Comment by gbe0** [comment]
@djaffer I have not had any problems however I am not using the scheduling built in (I use [deck chores](https://github.com/funkyfuture/deck-chores) to handle scheduling).

Can you provide the full compose file? Have you tried enabling debug logging using `DEBUG_MODE`? If you execute a backup manually, does it work (try running `/etc/services.available/10-db-backup/run` in the container)?

**Comment by djaffer** [comment]
It doesn't trigger the backup. Mariadb latest has renamed mysql to mariadb. https://mariadb.com/kb/en/mysql-command-line-client/ Not sure if this is the cause.

Here is the docker-compose.

```
backup:
    image: tiredofit/db-backup:latest
    networks:
      - network
    volumes:
      - /test:/backup
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_NAME=test-db
      - DB_USER=
      - DB_PASS=
      - DB_TYPE=mysql
      - DB_DUMP_FREQ=15
      - DB_CLEANUP_TIME=120
      - MD5=TRUE
      - SPLIT_DB=FALSE
      - EXTRA_OPTS=--single-transaction
    restart: unless-stopped
    
```
