### ISSUE TITLE
InfluxDB2 backup not working

### ISSUE THREAD

**Issue by BlackScreen** [tiredofit/docker-db-backup#206]
### Summary

I can not get an InfluxDB2 backup working.
Maybe I am doing something wrong, then please tell me.
I succesfully use this great tool already for backups of Postgres and MySQL.

### Steps to reproduce

- use latest InfluxDB2 version
- use latest docker-db-backup version
- create all access token via Influx UI
- use config below

### What is the expected *correct* behavior?

The backup should work.

### Relevant logs and/or screenshots

```
[tiredofit/db-backup:3.7.5 21:19:35 /] $ backup-now
** Performing Manual Backup
2023-03-10.21:19:38 [NOTICE] ** [db-backup] Dumping Influx2 database: 'all'
2023/03/10 21:19:38 INFO: Downloading metadata snapshot
Error: failed to backup metadata: failed to download metadata snapshot: 401 Unauthorized: read:authorizations is unauthorized
2023-03-10.21:19:38 [ERROR] ** [db-backup] DB Backup of 'influx2_all_influxdb_20230310-211938' reported errors
2023-03-10.21:19:38 [ERROR] ** [db-backup] Skipping creating archive file because backup did not complete successfully
2023-03-10.21:19:38 [ERROR] ** [db-backup] Skipping Checksum creation because backup did not complete successfully
2023-03-10.21:19:38 [ERROR] ** [db-backup] Skipping moving DB Backup to final location because backup did not complete successfully
2023-03-10.21:19:38 [NOTICE] ** [db-backup] DB Backup for 'all' time taken: Hours: 0 Minutes: 00 Seconds: 00
2023-03-10.21:19:38 [INFO] ** [db-backup] Backup routines finish time: 2023-03-10 21:19:38 CET with overall exit code 1
2023-03-10.21:19:38 [NOTICE] ** [db-backup] Backup routines time taken: Hours: 0 Minutes: 00 Seconds: 00
2023-03-10.21:19:38 [ERROR] ** [db-backup] Skipping Cleaning up old backups because there were errors in backing up
```

### Environment
DB_TYPE=influx
DB_HOST=http://influxdb
DB_NAME=ALL
DB_USER=my_organization
DB_PASS=my_all_access_pass_from_influx_ui
DB_DUMP_FREQ=1440
DB_DUMP_BEGIN=0300
DB_CLEANUP_TIME=8640
INFLUX_VERSION=2
COMPRESSION=GZ
CONTAINER_ENABLE_MONITORING=FALSE

- Image version / tag: latest
- Host OS: Ubuntu 22.04

### docker-compose.yml
```
version: '3.7'

services:
  influxdb:
	image: influxdb:2.6-alpine
	container_name: influxdb
	restart: unless-stopped
	environment:
	  - DOCKER_INFLUXDB_INIT_MODE=setup
	  - DOCKER_INFLUXDB_INIT_USERNAME=my_admin_user
	  - DOCKER_INFLUXDB_INIT_PASSWORD=my_admin_password
	  - DOCKER_INFLUXDB_INIT_ORG=my_organization
	  - DOCKER_INFLUXDB_INIT_BUCKET=my_bucket
	  - INFLUXD_LOG_LEVEL=warn
	  - TZ=Europe/Berlin
	volumes:
	  - /etc/localtime:/etc/localtime:ro
	  - ./conf:/etc/influxdb2
	  - ./data:/var/lib/influxdb2
	networks:
	  - default

  influxdb-backup:
	image: tiredofit/db-backup
	container_name: influxdb-backup
	restart: unless-stopped
	environment:
	  - DB_TYPE=influx
	  - DB_HOST=http://influxdb
	  - DB_NAME=ALL
	  - DB_USER=my_organization
	  - DB_PASS=my_all_access_pass_from_influx_ui
	  - DB_DUMP_FREQ=1440
	  - DB_DUMP_BEGIN=0300
	  - DB_CLEANUP_TIME=8640
	  - INFLUX_VERSION=2
	  - COMPRESSION=GZ
	  - CONTAINER_ENABLE_MONITORING=FALSE
	volumes:
	  - /etc/localtime:/etc/localtime:ro
	  - ./backups:/backup
	depends_on:
	  - influxdb
	networks:
	  - default
```

Thanks for creating this tool and looking into it and helping me! :)
