### ISSUE TITLE
Allow multiple backup targets

### ISSUE THREAD

**Issue by jwillmer** [tiredofit/docker-db-backup#21]
You can define lists in environment variables. This way we could us the image to backup multiple targets without the need of hosting the image multiple times.

```
"MessageBusList:0:Name": "Test"
"MessageBusList:0:UserName": demo

```

**Comment by tiredofit** [comment]
Do you mean something like `DB2_HOST`,`DB2_NAME` ? I think that would be possible, but multiple time expressions may get a bit messy.

**Comment by jwillmer** [comment]
I use this in an internal project to define multiple targets, example for this project:

```
  example-db-backup:
    container_name: example-db-backup
    image: tiredofit/db-backup
    links:
     - example-db
    volumes:
      - ./backups:/backup
    environment:
      - DbTarget:0:DB_TYPE=mariadb
      - DbTarget:0:DB_HOST=maria-host
      - DbTarget:0:DB_NAME=maria-db-name
      - DbTarget:0:DB_USER=maria-user
      - DbTarget:0:DB_PASS=maria-pw
      - DbTarget:0:DB_DUMP_FREQ=1440

      - DbTarget:1:DB_TYPE=mysql
      - DbTarget:1:DB_HOST=mysql-host
      - DbTarget:1:DB_NAME=mysql-db-name
      - DbTarget:1:DB_USER=mysql-user
      - DbTarget:1:DB_PASS=mysql-pw
      - DbTarget:1:DB_DUMP_FREQ=1440
    restart: always
```
