### ISSUE TITLE
No backup of InfluxDB possible since April 1st

### ISSUE THREAD

**Issue by BlackScreen** [tiredofit/docker-db-backup#213]
### Summary

I am running the docker container to make a daily backup of my InfluxDB database.
Since April 1st it is not possible to run a backup. I was running the latest backup-version and the latest 2.6 InfluxDB. The same behaviour with version 2.7 of InfluxDB.

### Steps to reproduce

"backup-now" in the backup-container

### What is the expected *correct* behavior?

a succesful backup

### Relevant logs and/or screenshots

```
[tiredofit/db-backup:3.8.3 20:00:14 /] $ backup-now
** Performing Manual Backup
2023-04-06.20:00:19 [NOTICE] ** [db-backup] Dumping Influx2 database: 'all'
unknown arguments: backup --org MY_ORGANIZATION --host http://influxdb:8086 --token MY_SUPER_SECRET_TOKEN --compression none /tmp/backups/influx2_all_influxdb_20230406-200019
Usage of influx:
  -version
                        Display the version and exit.
  -path-prefix 'url path'
                        Path that follows the host and port
  -host 'host name'
                        Host to connect to.
  -port 'port #'
                        Port to connect to.
  -socket 'unix domain socket'
                        Unix socket to connect to.
  -database 'database name'
                        Database to connect to the server.
  -password 'password'
                        Password to connect to the server.  Leaving blank will prompt for password (--password '').
  -username 'username'
                        Username to connect to the server.
  -ssl
                        Use https for requests.
  -unsafeSsl
                        Set this when connecting to the cluster using https and not use SSL verification.
  -execute 'command'
                        Execute command and quit.
  -type 'influxql|flux'
                        Type specifies the query language for executing commands or when invoking the REPL.
  -format 'json|csv|column'
                        Format specifies the format of the server responses:  json, csv, or column.
  -precision 'rfc3339|h|m|s|ms|u|ns'
                        Precision specifies the format of the timestamp:  rfc3339, h, m, s, ms, u or ns.
  -consistency 'any|one|quorum|all'
                        Set write consistency level: any, one, quorum, or all
  -pretty
                        Turns on pretty print for the json format.
  -import
                        Import a previous database export from file
  -pps
                        How many points per second the import will allow.  By default it is zero and will not throttle importing.
  -path
                        Path to file to import
  -compressed
                        Set to true if the import file is compressed

Examples:

    # Use influx in a non-interactive mode to query the database "metrics" and pretty print json:
    $ influx -database 'metrics' -execute 'select * from cpu' -format 'json' -pretty

    # Connect to a specific database on startup and set database context:
    $ influx -database 'metrics' -host 'localhost' -port '8086'
2023-04-06.20:00:19 [ERROR] ** [db-backup] DB Backup of 'influx2_all_influxdb_20230406-200019' reported errors
2023-04-06.20:00:19 [ERROR] ** [db-backup] Skipping creating archive file because backup did not complete successfully
2023-04-06.20:00:19 [ERROR] ** [db-backup] Skipping Checksum creation because backup did not complete successfully
2023-04-06.20:00:19 [ERROR] ** [db-backup] Skipping moving DB Backup to final location because backup did not complete successfully
2023-04-06.20:00:19 [NOTICE] ** [db-backup] DB Backup for 'all' time taken: Hours: 0 Minutes: 00 Seconds: 00
2023-04-06.20:00:19 [INFO] ** [db-backup] Backup routines finish time: 2023-04-06 20:00:19 CEST with overall exit code 1
2023-04-06.20:00:19 [NOTICE] ** [db-backup] Backup routines time taken: Hours: 0 Minutes: 00 Seconds: 00
2023-04-06.20:00:19 [ERROR] ** [db-backup] Skipping Cleaning up old backups because there were errors in backing up
[tiredofit/db-backup:3.8.3 20:00:19 /] $
```

### Environment
- Image version / tag: 2.8.3
- Host OS: Ubuntu 22.04 LTS

<details>
<summary>docker-compose.yml</summary>

```
version: '3.7'

services:
  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=[InfluxDB_Admin_User]
      - DOCKER_INFLUXDB_INIT_PASSWORD=[InfluxDB_Admin_PW]
      - DOCKER_INFLUXDB_INIT_ORG=[InfluxDB_Organization]
      - DOCKER_INFLUXDB_INIT_BUCKET=[InfluxDB_Bucket]
      - INFLUXD_LOG_LEVEL=warn
      - TZ=Europe/Berlin
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf:/etc/influxdb2
      - ./data:/var/lib/influxdb2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.entrypoints=https"
      - "traefik.http.routers.influxdb.rule=Host(`mydomain.com`)"
      - "traefik.http.routers.influxdb.tls=true"
      - "traefik.http.routers.influxdb.tls.certresolver=http"
      - "traefik.http.routers.influxdb.middlewares=default@file"
      - "traefik.http.routers.influxdb.service=influxdb"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - default

  influxdb-backup:
    image: tiredofit/db-backup
    container_name: influxdb-backup
    restart: unless-stopped
    environment:
      - DB_TYPE=influx
      - DB_HOST=http://influxdb
      - DB_NAME=ALL
      - DB_USER=[InfluxDB_Organization]
      - DB_PASS=[InfluxDB_Admin_Token]
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0300
      - DB_CLEANUP_TIME=8640
      - INFLUX_VERSION=2
      - COMPRESSION=GZ
      - CONTAINER_ENABLE_MONITORING=FALSE
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./backups:/backup
    depends_on:
      - influxdb
    networks:
      - default

networks:
  proxy:
    external: true
```

</details>
