### ISSUE TITLE
I get the message Mariadb server 'db' is not accesible, ping works

### ISSUE THREAD

**Issue by aadje93** [tiredofit/docker-db-backup#238]
### Summary

Trying the manual backup to verify everything is working, i get the db is not accesible. I use ping to do a check if docker network is good and i can ping the "db" container fine (resolving in correct container name and ping <1ms)

the compose file is as follows for the db-backup part

```
services:
  #backup db

  backup-db:
    image: tiredofit/db-backup
    networks:
      - wordpress
    volumes:
      - ./backups:/backup
      #- ./post-script.sh:/assets/custom-scripts/post-script.sh
    environment:
      - TIMEZONE=Europe/Amsterdam
      - CONTAINER_ENABLE_MONITORING=FALSE
      - DEBUG_MODE=TRUE
      - DB_TYPE=mariadb
      - DB_HOST=db:3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DUMP_FREQ=1440           # backup every minute
      - DB_DUMP_BEGIN=0000      # backup starts immediately
      - DB_CLEANUP_TIME=10080         # clean backups they are older than 5 minute
      - CHECKSUM=SHA1
      - COMPRESSION=GZ
      - SPLIT_DB=FALSE
```

the same env variables are used in my web app which make it work fine. so credentials are good, or does it need the root acces? 

### Steps to reproduce

Start the container with code above, put a secondary web app next to it with same ENV credentials to acces the mariadb container and then the web app works fine, but the db-backup app gives error 

`[db-backup] MySQL/MariaDB Server 'db' is not accessible, retrying.. `

### What is the expected *correct* behavior?

Well i expect to let the program do a backup given the same .env credentials to it as my web app :) 

### Relevant logs and/or screenshots

```
[tiredofit/db-backup:3.9.7 09:58:11 /] $ backup-now
** Performing Manual Backup
2023-07-30.09:58:36 [WARN] ** [db-backup] MySQL/MariaDB Server 'db' is not accessible, retrying.. (5 seconds so far)


[tiredofit/db-backup:3.9.7 10:05:59 /] $ ping db
PING db (192.168.128.6) 56(84) bytes of data.
64 bytes from [redacted].[redacted] (192.168.128.6): icmp_seq=1 ttl=64 time=0.132 ms
64 bytes from [redacted].[redacted] (192.168.128.6): icmp_seq=2 ttl=64 time=0.134 ms
^C
--- db ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms

```

- Image version / tag:  tiredofit/db-backup:3.9.7
- Host OS: debian12

    
### Possible fixes
i'm not sure where its going wrong. i'm sorry.
