### ISSUE TITLE
DB Cleanup is deleting all files and subdirectories in DB dump directory

### ISSUE THREAD

**Issue by ObJuanK** [tiredofit/docker-db-backup#244]
### Summary

dbbackup running to back up a postgres DB every day at 3am. Backups dumped to filesystem as the docker host has a NFS file share mounted and using that to store the backups.
The NFS system is a Synology NAS running Resilio to sync to a secondary network device.
When using DB_CLEANUP_TIME, it appears to delete everything in the specified directory, subdirectories included. 

With Resilio in particular (some other rsync apps may work different) the cleanup process deletes the .sync directory which lives inside the syncing directory.

eg: 
Directory being synced
/mnt/nfs01/database/backups 

Files being deleted
/mnt/nfs01/database/backups/.sync
/mnt/nfs01/database/backups/database.gz
/mnt/nfs01/database/backups/database.gz.md5

The .sync directory contains information about the directory structure it is in and [a few more things](https://connect.resilio.com/hc/en-us/articles/360008641380-What-is-sync-directory)

### Steps to reproduce

You dont necessarily need Resilio for this, I believe any directory created inside where the backups are being dumped will work the same. But for my setup, I have explained it in the summary. Reproduce the steps by configuring your backup with the following environment variables and wait a couple of days. (adjust timings to make it run sooner)

```
  db-backup:
    container_name: db-backup
    image: tiredofit/db-backup:latest
    links:
     - database
    volumes:
      - nfs-data:/backup
    environment:
      #- DEBUG_MODE=TRUE
      - DB_TYPE=pgsql
      - DB_HOST=databasehost
      - DB_NAME=databasename
      - DB_USER=dbuser
      - DB_PASS=password
      - DB_PORT=5432
      - DB_DUMP_FREQ=1440            # backup every day
      - DB_DUMP_BEGIN=0300      # backup starts at 3am
      - DB_CLEANUP_TIME=1440         # clean backups they are older than 1 day
      - CHECKSUM=MD5
      - COMPRESSION=GZ
      - SPLIT_DB=TRUE
      - BACKUP_LOCATION=FILESYSTEM
    restart: always
```

### What is the expected *correct* behavior?

Expected behavior is that when the cleanup process runs, it should only delete the files it has backed up.

### Relevant logs and/or screenshots

Like a chump, I rebuilt the container with new variables in an effort to troubleshoot and did not maintain the logs. But I do recall seeing 

```
/mnt/nfs01/database/backups/.sync is a directory
```

### Environment

- Image version / tag:  latest
- Host OS: Ubuntu 22.04.3 LTS
- NAS: Synology DS920+
- Rsync Software: Resilio Synology Package - 2.7.2.1375-3152

    
### Possible fixes

Could it be possible to include a way to influence the cleanup process to be able to select if you want it to delete all content or limit to specific file extensions, or limit to current working directory (no subdirectorties), or ignore any hidden directories

Thank you
