### ISSUE TITLE
CREATE_LATEST_SYMLINK using absolute instead of relative path

### ISSUE THREAD

**Issue by rltas** [tiredofit/docker-db-backup#256]
### Summary

Links created via CREATE_LATEST_SYMLINK use absolute instead of relative paths that match the path inside the container but not that of the mounted volume as seen from the host system.

### Steps to reproduce

compose.yaml

```
services:
  db-backup:
    image: tiredofit/db-backup
    environment:
      DB_TYPE: mysql
      DB_HOST: axon-db
      DB_NAME: axon
      DB_USER: <user>
      DB_PASS: <pass>
      DB_DUMP_BEGIN: "0200"
      COMPRESSION: GZ
    volumes:
      - /srv/axon/db/backup:/backup
```

Resulting backup:

```
# ls -ahl /srv/axon/db/backup/
total 276K
drwxr-xr-x 3 root root 4,0K Okt  7 00:00 .
drwxr-xr-x 4 root root 4,0K Okt  6 21:37 ..
drwxr-xr-x 2 root root 4,0K Okt  7 00:00 archive
lrwxrwxrwx 1 root root   49 Okt  7 00:00 latest-mysql_axon_axon-db -> /backup/mysql_axon_axon-db_20231007-020001.sql.gz
-rw-r--r-- 1 root root 257K Okt  7 00:00 mysql_axon_axon-db_20231007-020001.sql.gz
-rw-r--r-- 1 root root   76 Okt  7 00:00 mysql_axon_axon-db_20231007-020001.sql.gz.md5
```

### What is the expected *correct* behavior?

```
lrwxrwxrwx 1 root root   49 Okt  7 00:00 latest-mysql_axon_axon-db -> mysql_axon_axon-db_20231007-020001.sql.gz
```

    
### Possible fixes

https://github.com/tiredofit/docker-db-backup/blob/main/install/assets/functions/10-db-backup#L713

```
if var_true "${CREATE_LATEST_SYMLINK}" ; then
    ln -sf "${DB_DUMP_TARGET}"/"${target}" "${DB_DUMP_TARGET}"/latest-"${ltarget}"
fi
```

Either use ln from coreutils instead of busybox with the --relative argument

```
if var_true "${CREATE_LATEST_SYMLINK}" ; then
    ln -sfr "${DB_DUMP_TARGET}"/"${target}" "${DB_DUMP_TARGET}"/latest-"${ltarget}"
fi
```

or switch to the dump target directory first

```
if var_true "${CREATE_LATEST_SYMLINK}" ; then
    pushd "${DB_DUMP_TARGET}"
    ln -sfr "${target}" latest-"${ltarget}"
    popd
fi
```
