### ISSUE TITLE
DB backup doesn't performed on Ubuntu 18.04

### ISSUE THREAD

**Issue by dajnz** [tiredofit/docker-db-backup#26]
Hello,
thank you for this tool, but unfortunately, it looks like I have an issue with it.

I added this backup tool as an additional service to my docker-compose file like this:
```
...

  dbbackup:
    image: tiredofit/db-backup:latest
    container_name: db-backupper
    environment:
      DB_TYPE: pgsql
      DB_HOST: storage-db
      DB_NAME: storage_db
      DB_USER: postgres
      DB_PASS: ${POSTGRES_PASSWORD}
      # Test db backup each 3 minutes
      DB_DUMP_FREQ: 3
      # Cleanup backups older than 3 days
      DB_CLEANUP_TIME: 4320
    depends_on:
      - db
    networks:
      - my-network
    volumes:
      - ${DB_BACKUP_DIR}:/backup
```
I just added the line with more frequent DB backupping for debugging.

On my local computer with Ubuntu 16.04, it works just fine, but after I pushed my services on a remote server under Ubuntu 18.04 I see no backups at all. 

Checking logs with `docker logs CONTAINER-NAME` gives the output below, and as I see it the only suspicious line is **s6-svc: fatal: unable to control /var/run/s6/services/-d: No such file or directory**, but my knowledge of that system stuff is very limited.

```Dockerfile
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 00-functions: applying... 
[fix-attrs.d] 00-functions: exited 0.
[fix-attrs.d] 01-s6: applying... 
[fix-attrs.d] 01-s6: exited 0.
[fix-attrs.d] 02-zabbix: applying... 
[fix-attrs.d] 02-zabbix: exited 0.
[fix-attrs.d] 03-logrotate: applying... 
[fix-attrs.d] 03-logrotate: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-startup: executing... 
[cont-init.d] 00-startup: exited 0.
[cont-init.d] 01-timezone: executing... 
[NOTICE] ** [timezone] Setting timezone to 'America/Vancouver'
[cont-init.d] 01-timezone: exited 0.
[cont-init.d] 02-permissions: executing... 
[cont-init.d] 02-permissions: exited 0.
[cont-init.d] 03-zabbix: executing... 
[NOTICE] ** [zabbix] Disabling Zabbix Monitoring Functionality
s6-svc: fatal: unable to control /var/run/s6/services/-d: No such file or directory
[cont-init.d] 03-zabbix: exited 0.
[cont-init.d] 04-cron: executing... 
[NOTICE] ** [cron] Disabling Cron
[cont-init.d] 04-cron: exited 0.
[cont-init.d] 05-smtp: executing... 
[NOTICE] ** [smtp] Disabling SMTP Features
[cont-init.d] 05-smtp: exited 0.
[cont-init.d] 99-container: executing... 
[cont-init.d] 99-container: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

Maybe you have some ideas about what's went wrong? Thank you for your time.
