### ISSUE TITLE
pg_dumpall version mismatched

### ISSUE THREAD

**Issue by tamimology** [tiredofit/docker-db-backup#261]
### Summary

I have Postgres db and it is not being backed up as there is a mismatch in the pg_dumpall version

### Relevant logs and/or screenshots

```
2023-10-22T13:50:06.465050946Z pg_dumpall: error: aborting because of server version mismatch
2023-10-22T13:50:06.478788058Z pg_dumpall: detail: server version: 16.0; pg_dumpall version: 15.4
```

### Environment

- Image version / tag:  3.11.0 
- Host OS: Synology DS1513+ (DSM 6.4)

<details>
<summary>Any logs | docker-compose.yml</summary>

```
  postgres:
    container_name: postgres
    restart: always
    volumes:
      - $PERSIST/pg-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: $DB_PASSWORD
    security_opt:
      - no-new-privileges:true
    user: $PUID:$PGID
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "pgdb", "-U", "pguser"]
      timeout: 45s
      interval: 10s
      retries: 10
    image: 'postgres:alpine'
```

```
  postgres-backup:
    container_name: postgres-backup
    restart: always
    volumes:
      - $BACKUPS/postgres:/backup
    environment:
      - TIMEZONE=$TZ
      - DB_TYPE=pgsql
      - DB_HOST=postgres
      - DB_NAME=pgdb
      - DB_USER=pguser
      - DB_PASS=$DB_PASSWORD
      - DB_DUMP_FREQ=1440 #once per day
      - DB_DUMP_BEGIN=0050 # @00:45 midnight
      - DB_CLEANUP_TIME=8640 # keep for 6 days
      - CHECKSUM=SHA1
      - COMPRESSION=ZSTD
      - COMPRESSION_LEVEL=10
      - SPLIT_DB=FALSE
      - MYSQL_SINGLE_TRANSACTION=true
      - CONTAINER_ENABLE_MONITORING=FALSE
    links:
     - postgres
    image: 'tiredofit/db-backup:latest'
```
</details>
