### ISSUE TITLE
InfluxDB backup not doing anything

### ISSUE THREAD

**Issue by JvdMaat** [tiredofit/docker-db-backup#270]
### Summary

Just trying out 4.0.4, but my InfluxDB2 backup does not seem to be doing anything. Nor does the debug level seem to give any info.

### Steps to reproduce

This is my docker-compose section:
```
  db-backup:
    container_name: db-backup
    image: tiredofit/db-backup:4.0.4 #${DBBACKUP_VERSION}
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
#      - USER_DBBACKUP=${PUID}
#      - GROUP_DBBACKUP=${GUID}
      - TZ=${TZ}
#      - DEFAULT_RESOURCE_OPTIMIZED=TRUE
      - DEFAULT_COMPRESSION=GZ
#      - DEFAULT_COMPRESSION_LEVEL=6
      - DEFAULT_GZ_RESYNCABLE=TRUE
      - DEFAULT_CHECKSUM=NONE
#      - DEFAULT_BACKUP_BLACKOUT_BEGIN='0700'
#      - DEFAULT_BACKUP_BLACKOUT_END=2200
      - DEFAULT_LOG_LEVEL=DEBUG
      - DB01_TYPE=influx
      - DB01_INFLUX_VERSION=2
      - DB01_HOST=https://${DOCKERHOST}
      - DB01_NAME=homeassistant
      - DB01_USER=myuser
      - DB01_PASS=${HAINFLUXDBPWD}
      - DB01_BACKUP_BEGIN=1628      # backup starts at 23:30
      - DB01_CLEANUP_TIME=2500      # clean backups from 2 days ago
      - DB01_FILESYSTEM_PATH=/backup/influxdbha
#      - DB01_MYSQL_ENABLE_TLS=TRUE  # is this needed?
      #- CONTAINER_ENABLE_MONITORING=FALSE
    depends_on:
      - influxdbha
    #healthcheck: Needed
    volumes:
      - ${DOCKERPATH}${DBBACKUPPATH}/backup:/backup
      - ${DOCKERPATH}${DBBACKUPPATH}/logs:/logs
```
(In my attempt to fix this I have commented out a bunch of DEFAULT options that I added for the 4.0.4 version)

### What is the expected *correct* behavior?

Backup files showing up in the target location. This was working with 3.12.0

### Relevant logs and/or screenshots

```
                                                                       ,---.
,--------.,--.                 ,--.            ,---.    ,--. ,--------.|   |
'--.  .--'`--',--.--. ,---.  ,-|  |     ,---. /  .-'    |  | '--.  .--'|  .'
   |  |   ,--.|  .--'| .-. :' .-. |    | .-. ||  `-,    |  |    |  |   |  |
   |  |   |  ||  |   \   --.\ `-' |    ' '-' '|  .-'    |  |.--.|  |   `--'
   `--'   `--'`--'    `----' `---'      `---' `--'      `--''--'`--'   .--.
                                                                       '--'
Image:  tiredofit/db-backup | Version  4.0.4 Type 'image_changelog' for details
Repository/Documentation: https://github.com/tiredofit/docker-db-backup/
If this image provides you value  - Consider sponsoring my work for continued 
development, timely updates, and feature requests. Commercial support available.
                    More Info:  https://www.tiredofit.ca
2023-11-09.16:26:50 [NOTICE] ** [monitoring] Container configured for monitoring with 'zabbix modern'
2023-11-09.16:26:50 [NOTICE] ** [scheduling] Container configured for scheduled tasks with 'cron'
2023-11-09.16:26:51 [STARTING] ** [monitoring] [1] Starting Zabbix Agent (modern) 6.4.8
2023-11-09.16:26:52 [STARTING] ** [scheduling] [1] Starting cron
2023-11-09.16:26:53 [INFO] ** [01-https://host.domain.com__homeassistant] Next Backup at 2023-11-09 16:28:00 EST
2023-11-09.16:28:00 [INFO] ** [01-https://host.domain.com__homeassistant] Backup 01 routines finish time: 2023-11-09 16:28:00 EST with exit code 0
2023-11-09.16:28:00 [NOTICE] ** [01-https://host.domain.com__homeassistant] Backup 01 routines time taken: Hours: 0 Minutes: 00 Seconds: 00
2023-11-09.16:28:00 [NOTICE] ** [01-https://host.domain.com__homeassistant] Sleeping for another 86400 seconds. Waking up at 2023-11-10 16:28:00 EST 
```
### Environment

- Image version / tag:  4.0.4
- Host OS: Ubuntu

The DB01_ variables are all copied 1:1 from a working 3.12.0 config, so I know in principle this should work.

I had DEFAULT_LOG_LEVEL at ERROR and now DEBUG, but the docker logs show the same NOTICE and INFO lines.
