### ISSUE TITLE
Postgres backup not working anymore after updating to V4

### ISSUE THREAD

**Issue by BlackScreen** [tiredofit/docker-db-backup#271]
### Summary

I have updated the docker image to V4.0.4 and tried it with the Postgres DB (I have also an InfluxDB and a MariaDB but did not test them yet) - it is not working. Changed everything according to the docs.

### Steps to reproduce

My old, working docker-compose section from V3:

```
  healthchecks-backup:
    image: tiredofit/db-backup
    container_name: healthchecks-backup
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - DB_TYPE=pgsql
      - DB_HOST=healthchecks-db
      - DB_NAME=healthchecks
      - DB_USER=postgres
      - DB_PASS=password
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0300
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=GZ
      - CONTAINER_ENABLE_MONITORING=FALSE
      - TZ=Europe/Berlin
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./backups:/backup
    depends_on:
      - healthchecks-db
    networks:
      - default
```

The edited, not working docker-compose section for V4:

```
  healthchecks-backup:
    image: tiredofit/db-backup
    container_name: healthchecks-backup
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - DB01_TYPE=pgsql
      - DB01_HOST=healthchecks-db
      - DB01_NAME=healthchecks
      - DB01_USER=postgres
      - DB01_PASS=password
      - DEFAULT_BACKUP_BEGIN=0300
      - DEFAULT_BACKUP_INTERVAL=1440
      - DEFAULT_CLEANUP_TIME=8640
      - DEFAULT_COMPRESSION=GZ
      - CONTAINER_ENABLE_MONITORING=FALSE
      - TZ=Europe/Berlin
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./backups:/backup
    depends_on:
      - healthchecks-db
    networks:
      - default
```

### What is the expected *correct* behavior?

A working backups as before. I did not change anything in the DB-variables (except the "01") and did not change anything in the rest of the compose file. Do I have to use the "01" when I am just exporting one DB?

### Relevant logs and/or screenshots

```
[tiredofit/db-backup:4.0.4 01:17:54 /] $ backup-now
2023-11-10.01:17:59 [INFO] ** [db-backup01] Starting Manual Backup for db-backup01
2023-11-10.01:17:59 [NOTICE] ** [01-healthchecks-db__healthchecks] Dumping PostgresSQL database: 'healthchecks' and compressing with 'gzip'
pg_dump: error: connection to server at "healthchecks-db" (172.22.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"
2023-11-10.01:18:00 [INFO] ** [01-healthchecks-db__healthchecks] DB Backup of 'pgsql_healthchecks_healthchecks-db_20231110-011759.sql.gz' completed successfully
2023-11-10.01:18:00 [NOTICE] ** [01-healthchecks-db__healthchecks] Generating MD5 sum for 'pgsql_healthchecks_healthchecks-db_20231110-011759.sql.gz'
2023-11-10.01:18:00 [NOTICE] ** [01-healthchecks-db__healthchecks] Backup of 'pgsql_healthchecks_healthchecks-db_20231110-011759.sql.gz' created with the size of 20 bytes
2023-11-10.01:18:00 [NOTICE] ** [01-healthchecks-db__healthchecks] DB Backup for 'healthchecks' time taken: Hours: 0 Minutes: 00 Seconds: 01
2023-11-10.01:18:00 [INFO] ** [01-healthchecks-db__healthchecks] Backup 01 routines finish time: 2023-11-10 01:18:00 CET with exit code 0
2023-11-10.01:18:00 [NOTICE] ** [01-healthchecks-db__healthchecks] Backup 01 routines time taken: Hours: 0 Minutes: 00 Seconds: 01
```

### Environment

- Image version / tag:  4.0.4
- Host OS: Ubuntu 22.04 LTS

I have no idea why it is complaining about the password. I did not touch that at all. The application using that DB is working as expected. Weird. Thanks for your help! :)
