### ISSUE TITLE
Won't backup after upgrade to V4 config - issue with passing password perhaps?

### ISSUE THREAD

**Issue by bossanova808** [tiredofit/docker-db-backup#274]
### Summary

Have had this working well for some time now.  So, first let me say thank-you, it's a very handy container and I have been safely able to restore DBs a number of times after experiments and 'adventures'.

I recently noticed the warnings about deprecations, on upgrading the container, so proceeded to update config to V4.

Now, it unfortunately won't backup at all:
`MySQL/MariaDB Server 'db' is not accessible, retrying.. (10 seconds so far)` etc forever

The issue _appears_ to be with the exporting of the password (I am thinking quote issues, and/or with the `!` character)

...if, in the container, I manually do:
```
[tiredofit/db-backup:4.0.6 15:30:27 /] $EXPORT MYSQL_PWD='xxx!'
[tiredofit/db-backup:4.0.6 15:30:30 /] $ mysqladmin -uroot -P3306 -hdb status
Uptime: 2644  Threads: 2  Questions: 9  Slow queries: 0  Opens: 17  Open tables: 10  Queries per second avg: 0.003
```
...it works ok.

But the same command in the actual `backup-now` run is failing as per the logs below.

In my `.env` I have:

`MARIADB_PASSWORD="xxx!"`

and the compose environment bit is:

`- "DB01_PASS=${MARIADB_PASSWORD}"`

(rest is below).  

This approach to the password has worked without issues for some time previously, and works fine this way with other containers etc.  I.e. the password itself (and env var) is categorically correct as it's used in other containers with no issues

...basic checks are fine - e.g. I can ping the db container from bash with no issue:

```
[tiredofit/db-backup:4.0.6 15:16:23 /] $ ping db
PING db (172.18.0.9) 56(84) bytes of data.
64 bytes from db.docker_default (172.18.0.9): icmp_seq=1 ttl=64 time=0.174 ms
64 bytes from db.docker_default (172.18.0.9): icmp_seq=2 ttl=64 time=0.095 ms
64 bytes from db.docker_default (172.18.0.9): icmp_seq=3 ttl=64 time=0.096 ms
``` 

Relevant sections from docker compose:

```
    db:
        image: mariadb:latest
        container_name: db   
        environment:
            - PUID=${UID}
            - PGID=${GUID}
            - TZ=${TZ}
            - "MARIADB_ROOT_PASSWORD_HASH=${MARIADB_ROOT_PASSWORD_HASH}"
            - MARIADB_AUTO_UPGRADE=1
        volumes:
            - ${MARIADB_OFFICIAL_CONF}:/etc/mysql/conf.d
            - ${MARIADB_OFFICIAL_DATA}:/var/lib/mysql
        ports:
            - 3306:3306
        restart: unless-stopped

    # https://github.com/tiredofit/docker-db-backup
    db-backup:
        container_name: db-backup
        image: tiredofit/db-backup:latest     
        links:
            - db
        # 1440 = one day, 20160 = two weeks    
        environment:
            - TZ=${TZ}
            - DB01_TYPE=mysql
            - DB01_HOST=db
            - DB01_NAME=ALL
            - DB01_USER=root
            - DB01_NAME_EXCLUDE=information_schema,performance_schema,mysql,sys
            - "DB01_PASS=${MARIADB_PASSWORD}"
            - DB_BACKUP_INTERVAL=1440
            - DB_BACKUP_BEGIN=1405
            # No longer an option I think, was defaulted to true...
            # - SPLIT_DB=TRUE
            - DEFAULT_COMPRESSION=GZ
            - MD5=FALSE
            - DB_CLEANUP_TIME=20160
            - CONTAINER_ENABLE_MONITORING=FALSE
            - DEBUG_MODE=TRUE
        volumes:
            - ${MARIADB_BACKUPS}:/backup
            #- ./post-script.sh:/assets/custom-scripts/post-script.sh
        restart: unless-stopped
```

Debug:

```
2023-11-11.15:10:32 [DEBUG] /etc/services.available/dbbackup-01/run ** [01-db__ALL] Backup 01 routines started time: 2023-11-11 15:10:32 AEDT
+ bootstrap_filesystem
+ var_true ''
+ '[' '' = true ']'
+ '[' '' = yes ']'
+ '[' '!' -d /backup ']'
++ stat -c %U /backup
+ '[' UNKNOWN '!=' dbbackup ']'
+ chown -R dbbackup:dbbackup /backup
++ stat -c %a /backup
+ '[' 700 '!=' 600 ']'
+ chmod -R 600 /backup
+ '[' -d /backup/archive/ ']'
+ '[' '!' -d /logs ']'
+ mkdir -p /logs
++ stat -c %U /logs
+ '[' root '!=' dbbackup ']'
+ chown -R dbbackup:dbbackup /logs
++ date +%Y%m%d
+ '[' '!' -d /logs/20231111 ']'
++ date +%Y%m%d
+ run_as_user mkdir -p /logs/20231111
+ sudo -u dbbackup mkdir -p /logs/20231111
++ stat -c %a /logs
+ '[' 755 '!=' 755 ']'
+ '[' '!' -d /tmp/backups ']'
+ mkdir -p /tmp/backups
++ stat -c %U /tmp/backups
+ '[' root '!=' dbbackup ']'
+ chown -R dbbackup:dbbackup /tmp/backups
+ var_true ''
+ '[' '' = true ']'
+ '[' '' = yes ']'
+ check_availability
+ var_true ''
+ '[' '' = true ']'
+ '[' '' = yes ']'
+ var_false FALSE
+ '[' false = false ']'
+ case "${dbtype}" in
+ counter=0
+ export 'MYSQL_PWD='\''xxx!'\'''
+ MYSQL_PWD=''\''xxx!'\'''
+ run_as_user mysqladmin -uroot -P3306 -hdb status
+ sleep 5
+ ((  counter+=5  ))
+ write_log warn 'MySQL/MariaDB Server '\''db'\'' is not accessible, retrying.. (5 seconds so far)'
+ var_true ''
+ '[' '' = true ']'
+ '[' '' = yes ']'
+ output_off
+ '[' true = true ']'
+ set +x
2023-11-11.15:10:37 [WARN] /etc/services.available/dbbackup-01/run ** [01-db__ALL] MySQL/MariaDB Server 'db' is not accessible, retrying.. (5 seconds so far)
```

### Environment

- Image version / tag:  
- Host OS: Ubuntu 22.04 LTS
