### ISSUE TITLE
Backup System doesn't work when just using a mongodb custom URI

### ISSUE THREAD

**Issue by Luc1412** [tiredofit/docker-db-backup#275]
### Summary

The mentioned `backup-now` command isn't available in V4

### Steps to reproduce

1. Enter the container with the mentioned command: `bash docker exec -it NAME bash`
2. type `backup-now`

### What is the expected *correct* behavior?

A backup will be created

### Relevant logs and/or screenshots

`bash: backup-now: command not found`

### Environment

- Image version / tag:  `:latest` (4.0.11)
- Host OS: `Linux easy-system 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux`

```yml
  mongo-backup:
    image: ghcr.io/tiredofit/docker-db-backup:latest
    environment:
      - MODE=MANUAL
      - DB01_TYPE=mongo
      - DB01_NAME=ALL
      - DB01_MONGO_CUSTOM_URI=${MONGO_URI}
      - DB01_DUMP_FREQ=1440
      - DB01_DUMP_BEGIN=0300
      - DB01_CLEANUP_TIME=43200
      - CONTAINER_ENABLE_MONITORING=FALSE
    volumes:
      - ...:/backup
    depends_on:
      - mongo1
    networks:
      - default
```
