### ISSUE TITLE
SQLite cron issue

### ISSUE THREAD

**Issue by JanickGers85** [tiredofit/docker-db-backup#296]
### Summary

Backup is executed immediately after the container start and loops to infinite. 
MariaDB backup with cron seems working correctly. 

### Steps to reproduce

1. Schedule a backup with the cron `0 * * * *`
2. Start the container

### What is the expected *correct* behavior?

Backup is executed according to the cron. 

### Relevant logs and/or screenshots

```
,---.
,--------.,--.                 ,--.            ,---.    ,--. ,--------.|   |
'--.  .--'`--',--.--. ,---.  ,-|  |     ,---. /  .-'    |  | '--.  .--'|  .'
   |  |   ,--.|  .--'| .-. :' .-. |    | .-. ||  `-,    |  |    |  |   |  |
   |  |   |  ||  |   \   --.\ `-' |    ' '-' '|  .-'    |  |.--.|  |   `--'
   `--'   `--'`--'    `----' `---'      `---' `--'      `--''--'`--'   .--.
                                                                       '--'
Image:  tiredofit/db-backup | Version  4.0.22 Type 'image_changelog' for details
Repository/Documentation: https://github.com/tiredofit/docker-db-backup/

If this image provides you value  - Consider sponsoring my work for continued
development, timely updates, and feature requests. Commercial support available.

                    More Info:  https://www.tiredofit.ca

2023-11-28.10:45:29 [NOTICE] ** [timezone] Timezone: Setting to 'Europe/Rome' from 'Etc/GMT'
2023-11-28.11:45:29 [NOTICE] ** [scheduling] Container configured for scheduled tasks with 'cron'
2023-11-28.11:45:30 [NOTICE] ** [messaging] Container configured to route mail via SMTP to 'postfix-relay'
2023-11-28.11:45:31 [STARTING] ** [scheduling] [1] Starting cron
2023-11-28.11:45:33 [INFO] ** [01-192.168.1.217__ALL] Next Backup at 2023-11-29 03:30:00 CET
/assets/functions/10-db-backup: line 1914: [: : integer expression expected
2023-11-28.11:45:34 [INFO] ** [02-_tobackup_db.sqlite3__ALL] Next Backup at 2023-11-28 11:00:00 CET
2023-11-28.11:45:34 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Dumping sqlite3 database: '/tobackup/db.sqlite3'
2023-11-28.11:45:34 [INFO] ** [02-_tobackup_db.sqlite3__ALL] DB Backup of 'sqlite3_db_20231128-114534.sqlite3' completed successfully
2023-11-28.11:45:34 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Generating SHA1 sum for 'sqlite3_db_20231128-114534.sqlite3.gz'
2023-11-28.11:45:34 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Backup of 'sqlite3_db_20231128-114534.sqlite3.gz' created with the size of 361172 bytes
2023-11-28.11:45:35 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] DB Backup for 'db' time taken: Hours: 0 Minutes: 00 Seconds: 01
2023-11-28.11:45:35 [INFO] ** [02-_tobackup_db.sqlite3__ALL] Cleaning up old backups on filesystem
2023-11-28.11:45:35 [INFO] ** [02-_tobackup_db.sqlite3__ALL] Backup 02 routines finish time: 2023-11-28 11:45:35 CET with exit code 0
2023-11-28.11:45:35 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Backup 02 routines time taken: Hours: 0 Minutes: 00 Seconds: 01
/assets/functions/10-db-backup: line 1914: [: : integer expression expected
2023-11-28.11:45:35 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Sleeping for another -2700 seconds. Waking up at 2023-11-28 11:00:00 CET
2023-11-28.11:45:35 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Dumping sqlite3 database: '/tobackup/db.sqlite3' and compressing with 'gzip'
2023-11-28.11:45:35 [INFO] ** [02-_tobackup_db.sqlite3__ALL] DB Backup of 'sqlite3_db_20231128-114535.sqlite3' completed successfully
2023-11-28.11:45:35 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Generating SHA1 sum for 'sqlite3_db_20231128-114535.sqlite3.gz'
2023-11-28.11:45:36 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Backup of 'sqlite3_db_20231128-114535.sqlite3.gz' created with the size of 361172 bytes
2023-11-28.11:45:36 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] DB Backup for 'db' time taken: Hours: 0 Minutes: 00 Seconds: 01
2023-11-28.11:45:36 [INFO] ** [02-_tobackup_db.sqlite3__ALL] Cleaning up old backups on filesystem
2023-11-28.11:45:36 [INFO] ** [02-_tobackup_db.sqlite3__ALL] Backup 02 routines finish time: 2023-11-28 11:45:36 CET with exit code 0
2023-11-28.11:45:36 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Backup 02 routines time taken: Hours: 0 Minutes: 00 Seconds: 01
/assets/functions/10-db-backup: line 1914: [: : integer expression expected
2023-11-28.11:45:36 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Sleeping for another -2700 seconds. Waking up at 2023-11-28 11:00:00 CET
2023-11-28.11:45:36 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Dumping sqlite3 database: '/tobackup/db.sqlite3' and compressing with 'gzip'
2023-11-28.11:45:36 [INFO] ** [02-_tobackup_db.sqlite3__ALL] DB Backup of 'sqlite3_db_20231128-114536.sqlite3' completed successfully
2023-11-28.11:45:36 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Generating SHA1 sum for 'sqlite3_db_20231128-114536.sqlite3.gz'
2023-11-28.11:45:36 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Backup of 'sqlite3_db_20231128-114536.sqlite3.gz' created with the size of 361172 bytes
2023-11-28.11:45:37 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] DB Backup for 'db' time taken: Hours: 0 Minutes: 00 Seconds: 01
2023-11-28.11:45:37 [INFO] ** [02-_tobackup_db.sqlite3__ALL] Cleaning up old backups on filesystem
2023-11-28.11:45:37 [INFO] ** [02-_tobackup_db.sqlite3__ALL] Backup 02 routines finish time: 2023-11-28 11:45:37 CET with exit code 0
2023-11-28.11:45:37 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Backup 02 routines time taken: Hours: 0 Minutes: 00 Seconds: 01
/assets/functions/10-db-backup: line 1914: [: : integer expression expected
2023-11-28.11:45:37 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Sleeping for another -2700 seconds. Waking up at 2023-11-28 11:00:00 CET
2023-11-28.11:45:37 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Dumping sqlite3 database: '/tobackup/db.sqlite3' and compressing with 'gzip'
2023-11-28.11:45:37 [INFO] ** [02-_tobackup_db.sqlite3__ALL] DB Backup of 'sqlite3_db_20231128-114537.sqlite3' completed successfully
2023-11-28.11:45:37 [NOTICE] ** [02-_tobackup_db.sqlite3__ALL] Generating SHA1 sum for 'sqlite3_db_20231128-114537.sqlite3.gz
```

### Environment

- Image version / tag:  4.0.22
- Host OS: Debian 12.2

<details>
<summary>Any logs | docker-compose.yml</summary>

```yaml
version: '3.6'
services:
  db-backup:
    container_name: dbbackup
    image: tiredofit/db-backup
    volumes:
      - ./docker/db-backups:/backup
      - ./docker/***:/tobackup
    environment:
      - TIMEZONE=Europe/Rome
      - CONTAINER_ENABLE_MONITORING=FALSE
      - DEFAULT_CHECKSUM=SHA1
      - DEFAULT_COMPRESSION=GZ
      - DEFAULT_CLEANUP_TIME=720
      - BACKUP_JOB_CONCURRENCY=2
      - DB01_FILESYSTEM_PATH=/backup/mariadb
      - DB01_TYPE=mysql
      - DB01_HOST=192.168.1.217
      - DB01_NAME=ALL
      - DB01_USER=root
      - DB01_PASS=***
      - DB01_BACKUP_BEGIN="30 3 * * *"
#      - DB01_BACKUP_BEGIN=0330
#      - DB01_BACKUP_INTERVAL=1440
      - DB02_TYPE=sqlite3
      - DB02_FILESYSTEM_PATH=/backup/***
      - DB02_HOST=/tobackup/db.sqlite3
      - DB02_NAME=ALL
      - DB02_BACKUP_BEGIN="0 * * * *"
#      - DB02_BACKUP_BEGIN=1300
#      - DB02_BACKUP_INTERVAL=60
``` 

</details>

 
    
### Possible fixes

Don't know
