### ISSUE TITLE
MSSQL issue to backup

### ISSUE THREAD

**Issue by farzadha2** [tiredofit/docker-db-backup#299]
### Summary

Hi Currently having issue to backup MSSQL on windows, 
1) the compression is not working, when activated does not backup to the s3 bucket, but if deactivated works correctly

2) its not deleting the .bak from the temp route

### Steps to reproduce

Very important because the MSSQL is a windows i had to cifs mount the shared route if not it wont work

`mount -t cifs //192.168.0.18/tmp /root/bakssql/temporal --verbose -o vers=2.1,user=administrador,password=mypasss,domain=mydomain`

1) This is the docker compose, using S3 minio bucket which gets error on the backup when having GZ 

```

services:
  example-mssql-db-backup:
    container_name: example-mssql-db-backup
    image: tiredofit/db-backup:latest
    volumes:
      - ./backups:/backup
      - ./temporal/backups/:/tmp/backups    # shared tmp backup directory
      #- ./post-script.sh:/assets/custom-scripts/post-script.sh
    environment:
      - TIMEZONE=America/Bogota
      - CONTAINER_ENABLE_MONITORING=FALSE
      - CONTAINER_NAME=example-mssql-db-backup
      - TEMP_PATH=/tmp/backups
      - DEFAULT_COMPRESSION=GZ
      - DEFAULT_CHECKSUM=NONE	
      - DEBUG_MODE=TRUE
      - DEBUG_BACKUP_MSSQL=TRUE
      - DEFAULT_BACKUP_LOCATION=S3
      - DEFAULT_S3_BUCKET=mssqlbucket
      - DEFAULT_S3_KEY_ID=miniouser
      - DEFAULT_S3_KEY_SECRET=mypass
      - DEFAULT_S3_HOST=192.168.0.210:9000
      - DEFAULT_S3_PROTOCOL=http
      - DEFAULT_S3_PATH=backup
      - DB01_TYPE=mssql
      - DB01_HOST=192.168.0.18
      - DB_PORT=2866
      - DB01_NAME=test
      - DB01_USER=sa
      - DB01_PASS=mypass
      - DB01_DUMP_INTERVAL=1400           # backup every minute
      - DB01_CLEANUP_TIME=1400         # clean backups they are older than 5 minute

```

2) it does not delete the .bak from the temp routes
```

root@dockers:~/bakssql/temporal/backups# ls -lah
total 6.4M
drwxr-xr-x 2 root root 8.0K Nov 29 23:42 .
drwxr-xr-x 2 root root    0 Nov 13 21:57 ..
-rwxr-xr-x 1 root root 3.2M Nov 29 23:39 mssql_test_192.168.0.18_20231129-233944.bak
-rwxr-xr-x 1 root root 3.2M Nov 29 23:42 mssql_test_192.168.0.18_20231129-234232.bak
```

### What is the expected *correct* behavior?

1) It should in theory backup with compress the .bak

2) and should delete .bak in the temp routes

### Relevant logs and/or screenshots

was to long to add it here

https://pastebin.com/6mHjkscd)

    
### Possible fixes

1)  reading the log it shows that .bak is created correctly in the temp 

```
+ write_log info 'DB Backup of '\''mssql_test_192.168.0.18_20231129-234704.bak.gz'\'' completed successfully'
+ var_true ''
+ '[' '' = true ']'
+ '[' '' = yes ']'
+ output_off
+ '[' true = true ']'
+ set +x
```

but later in the log it says cannot find the .gz 

```
++ run_as_user stat -c%s /tmp/backups/mssql_test_192.168.0.18_20231129-234704.bak.gz
++ sudo -Eu dbbackup stat -c%s /tmp/backups/mssql_test_192.168.0.18_20231129-234704.bak.gz
stat: cannot stat '/tmp/backups/mssql_test_192.168.0.18_20231129-234704.bak.gz': No such file or directory
+ dbbackup_size=
++ run_as_user date -r /tmp/backups/mssql_test_192.168.0.18_20231129-234704.bak.gz +%s
++ sudo -Eu dbbackup date -r /tmp/backups/mssql_test_192.168.0.18_20231129-234704.bak.gz +%s
date: /tmp/backups/mssql_test_192.168.0.18_20231129-234704.bak.gz: No such file or directory
+ dbbackup_date=
+ case "${backup_job_size_value,,}" in
+ backup_job_size_value=1
+ '[' 1 = 1 ']'
++ run_as_user stat -c%s /tmp/backups/mssql_test_192.168.0.18_20231129-234704.bak.gz
++ sudo -Eu dbbackup stat -c%s /tmp/backups/mssql_test_192.168.0.18_20231129-234704.bak.gz
stat: cannot stat '/tmp/backups/mssql_test_192.168.0.18_20231129-234704.bak.gz': No such file or directory
+ filesize=
```

2) which i assume thats why it does not delete it 
```

The user-provided path /tmp/backups/*. does not exist.
+ run_as_user rm -rf /tmp/backups/mssql_test_192.168.0.18_20231129-234704.bak.gz.
+ sudo -Eu dbbackup rm -rf /tmp/backups/mssql_test_192.168.0.18_20231129-234704.bak.gz.
+ run_as_user rm -rf /tmp/backups/mssql_test_192.168.0.18_20231129-234704.bak.gz
+ sudo -Eu dbbackup rm -rf /tmp/backups/mssql_test_192.168.0.18_20231129-234704.bak.gz
+ run_as_user rm -rf /tmp/backups/mssql_test_192.168.0.18_20231129-234704.bak.gz
+ sudo -Eu dbbackup rm -rf /tmp/backups/mssql_test_192.168.0.18_20231129-234704.bak.gz
+ var_true ''
+ '[' '' = true ']'
+ '[' '' = yes ']'
```
but in the container i can see the .bak but not the gz

```
[tiredofit/db-backup:4.0.25 23:53:05 /] $ ls -lah /tmp/backups/
total 9.5M
drwxr-xr-x 2 root root 8.0K Nov 29 23:47 .
drwxrwxrwt 1 root root 4.0K Nov 29 23:47 ..
-rwxr-xr-x 1 root root 3.2M Nov 29 23:39 mssql_test_192.168.0.18_20231129-233944.bak
-rwxr-xr-x 1 root root 3.2M Nov 29 23:42 mssql_test_192.168.0.18_20231129-234232.bak
-rwxr-xr-x 1 root root 3.2M Nov 29 23:47 mssql_test_192.168.0.18_20231129-234704.bak

```

Thank you
