### ISSUE TITLE
not backing up after the latest release

### ISSUE THREAD

**Issue by tamimology** [tiredofit/docker-db-backup#302]
### Summary

The container loads but never backs up any of the db. The same is seen for Postgres, MariaDB, Redis

### Steps to reproduce

included my docker-compose for the container as well as the logs

### What is the expected *correct* behavior?

Have backups in the designated folder

### Relevant logs and/or screenshots

```
                                                                       ,---.
,--------.,--.                 ,--.            ,---.    ,--. ,--------.|   |
'--.  .--'`--',--.--. ,---.  ,-|  |     ,---. /  .-'    |  | '--.  .--'|  .'
   |  |   ,--.|  .--'| .-. :' .-. |    | .-. ||  `-,    |  |    |  |   |  |
   |  |   |  ||  |   \   --.\ `-' |    ' '-' '|  .-'    |  |.--.|  |   `--'
   `--'   `--'`--'    `----' `---'      `---' `--'      `--''--'`--'   .--.
                                                                       '--'
Image:  tiredofit/db-backup | Version  4.0.25 Type 'image_changelog' for details
Repository/Documentation: https://github.com/tiredofit/docker-db-backup/

If this image provides you value  - Consider sponsoring my work for continued 
development, timely updates, and feature requests. Commercial support available.

                    More Info:  https://www.tiredofit.ca

2023-11-30.14:15:48 [NOTICE] ** [timezone] Timezone: Setting to 'Australia/Melbourne' from 'Etc/GMT'
2023-12-01.01:15:51 [NOTICE] ** [scheduling] Container configured for scheduled tasks with 'cron'
2023-12-01.01:15:58 [NOTICE] ** [messaging] Container configured to route mail via SMTP to 'postfix-relay'
2023-12-01.01:16:12 [STARTING] ** [scheduling] [1] Starting cron
2023-12-01.01:16:18 [INFO] ** [01-jellystat-postgres__jfstat] Next Backup at 2023-12-02 00:55:00 AEDT
```

### Environment

- Image version / tag:  4.0.25 / latest
- Host OS: Synology DSM 6.2.4

<details>

```  
jellystat-postgres-backup:
    container_name: jellystat-postgres-backup
    restart: always
    volumes:
      - $BACKUPS/postgres/jellystat:/backup
    environment:
      - TIMEZONE=$TZ
      - DB_TYPE=pgsql
      - DB_HOST=jellystat-postgres
      - DB_NAME=jfstat
      - DB_USER=jellystat
      - DB_PASS=$DB_PASSWORD
      - DEFAULT_BACKUP_INTERVAL=1440 #once per day
      - DEFAULT_BACKUP_BEGIN="0055" # @00:55 midnight
      - DB_CLEANUP_TIME=8640 # keep for 6 days
      - DEFAULT_CHECKSUM=SHA1
      - DEFAULT_COMPRESSION=ZSTD
      - DEFAULT_COMPRESSION_LEVEL=10
      - DEFAULT_MYSQL_SINGLE_TRANSACTION=true
      - CONTAINER_ENABLE_MONITORING=FALSE
    links:
     - jellystat-postgres
    image: 'tiredofit/db-backup:latest'
```

</details>
