### ISSUE TITLE
/tmp not getting cleared

### ISSUE THREAD

**Issue by downdrown** [tiredofit/docker-db-backup#305]
### Summary

`/tmp` is not getting cleared after backup is done.

### Steps to reproduce

- Set up an InfluxDB Backup, my dataset is > 1GB.
- Execute the Backup
- Check `/tmp/backup` for remaining files

### What is the expected *correct* behavior?

I'm not sure if this is actually an issue or just working as designed.
However I run the db backup on my Unraid server and mounted a NFS share where the backups get stored.
I noticed that the docker.img was growing larger and larger, when I checked the InfluxDB Backup container I noticed that it contains 15GiG of backup data.

If this just works "as designed" feel free to close the issue, I just was not sure if that was intentional or not.

### Relevant logs and/or screenshots

![image](https://github.com/tiredofit/docker-db-backup/assets/3913600/df9a83a7-40e8-4a1d-ad16-ece6463bdc12)

### Environment

- Image version / tag:  `tiredofit/db-backup:4.0.26`
- Host OS: Unraid

<details>
<summary>Any logs | docker-compose.yml</summary>

#### docker-compose.yml

```
version: "3"

volumes:
  backup-mariadb:
    external: true
  backup-influxdb:
    external: true
  backup-logs:
    driver: local
    
networks:
  db-backup:
    external: true
    
services:
  backup-mariadb:
    image: tiredofit/db-backup:${DOCKER_IMAGE_VERSION}
    container_name: backup-mariadb
    restart: always
    networks:
      - db-backup
    environment:
      - TIMEZONE=Europe/Vienna
      - CONTAINER_NAME=backup-mariadb
      - CONTAINER_ENABLE_MONITORING=FALSE
      - BACKUP_JOB_CONCURRENCY=1
      - DEFAULT_CHECKSUM=MD5
      - DEFAULT_COMPRESSION=GZ
      - DEFAULT_DUMP_INTERVAL=1440
      - DEFAULT_DUMP_BEGIN=0000
      - DEFAULT_CLEANUP_TIME=8640
      - DB01_TYPE=mariadb
      - DB01_HOST=${MARIADB_HOST}
      - DB01_NAME=ALL
      - DB01_NAME_EXCLUDE=${MARIADB_EXCLUDED_SCHEMAS}
      - DB01_USER=${MARIADB_USER}
      - DB01_PASS=${MARIADB_PASSWORD}
    volumes:
      - backup-mariadb:/backup
      - backup-logs:/logs

  backup-influxdb:
    image: tiredofit/db-backup:${DOCKER_IMAGE_VERSION}
    container_name: backup-influxdb
    restart: always
    networks:
      - db-backup
    environment:
      - TIMEZONE=Europe/Vienna
      - CONTAINER_NAME=backup-influxdb
      - CONTAINER_ENABLE_MONITORING=FALSE
      - BACKUP_JOB_CONCURRENCY=1
      - DEFAULT_CHECKSUM=MD5
      - DEFAULT_COMPRESSION=GZ
      - DEFAULT_DUMP_INTERVAL=1440
      - DEFAULT_DUMP_BEGIN=0000
      - DEFAULT_CLEANUP_TIME=8640
      - DB01_TYPE=influx
      - DB01_INFLUX_VERSION=2
      - DB01_HOST=${INFLUXDB_HOST}
      - DB01_NAME=ALL
      - DB01_USER=${INFLUXDB_USER}
      - DB01_PASS=${INFLUXDB_PASSWORD}
    volumes:
      - backup-influxdb:/backup
      - backup-logs:/logs
```

#### Env
```
DOCKER_IMAGE_VERSION=4.0.26
MARIADB_HOST=mariadb
MARIADB_USER=<SECURE_CREDENTIALS>
MARIADB_PASSWORD=<SECURE_CREDENTIALS>
MARIADB_EXCLUDED_SCHEMAS=sys,mysql
INFLUXDB_HOST=http://influxdb
INFLUXDB_USER=<SECURE_CREDENTIALS>
INFLUXDB_PASSWORD=<SECURE_CREDENTIALS>
```
</details>

    
### Possible fixes
 - Clean up `/tmp/backup` after db dump
