### ISSUE TITLE
--Feature Request-- support docker secrets

### ISSUE THREAD

**Issue by bd8392** [tiredofit/docker-db-backup#31]
I use the mariadb root user to backup (as I want always all my databases backuped). It would be really nice, if you can provide the password inside a docker secret to add some security =). I know you've a lot of amazing containers on github =). So if you need some help, I'll do what I can to support you =). Thanks for all this amazing contribution to the community =). Your container is the ONLY solution for docker swarm in combination with rancheros to backup multiple databases! really cool!

**Comment by tiredofit** [comment]
The latest releases of the base image `https://github.com/tiredofit/docker-alpine/blob/3.11/README.md` do not advertise it, but there is Docker Secrets support built into it, and a few lines of code just need to be added to this image. I have a few other things on the go and when there is time will work it in for the DB_PASS variable.

**Comment by tiredofit** [comment]
Specifically - this function, feel free to give it a try in the code and if you get it to work submit a PR and I'll merge it in.
````
## Docker Secrets Support
## usage: file_env VAR [DEFAULT]
##    ie: file_env 'XYZ_DB_PASSWORD' 'example'
##        (will allow for "$XYZ_DB_PASSWORD_FILE" to fill in the value of "$XYZ_DB_PASSWORD" from a file, especially for Docker's secrets feature)
function file_env () {
  local var="$1"
  local fileVar="${var}_FILE"
  local def="${2:-}"
  local val="$def"
  if [ "${!fileVar:-}" ]; then
    val="$(cat "${!fileVar}")"
  elif [ "${!var:-}" ]; then
    val="${!var}"
  fi
  if [ -z ${val} ]; then
    print_error "error: neither $var nor $fileVar are set but are required"
    exit 1
  fi
  export "$var"="$val"
  unset "$fileVar"
}
````

**Comment by bd8392** [comment]
Okay i'll Look into it...I've never programmed with secrets before, but I'll try :-) thanks for the help :-)

**Comment by tiredofit** [comment]
Try pulling `tiredofit/db-backup:develop` and apply secrets for DB_USER and DB_PASS. Let me know if you get success and I'll push an actual release.

**Comment by bd8392** [comment]
Wow that was amazing fast =) It's working perfectly great thanks for that =). Here Is a example configuratiuion that I used to test for your docs =):
```
version: '3.3'
services:
  tiredofit-db-backup-dev:
    image: tiredofit/db-backup:develop
    environment:
      COMPRESSION: NONE
      DB_CLEANUP_TIME: '2880'
      DB_DUMP_FREQ: '1440'
      DB_HOST: exampledb
      DB_USER_FILE: /database_user
      DB_PASS_FILE: /database_password
      DB_PORT: '0000'
      DB_TYPE: example
      MD5: 'TRUE'
      SPLIT_DB: 'TRUE'
      TIMEZONE: Europe/Vienna
    networks:
     - database_stack_net
    secrets:
     -
      source: db_root_password
      target: /database_password
     -
      source: db_root_user
      target: /database_user
    logging:
      driver: json-file
networks:
  database_stack_net:
    external: true
secrets:
  db_root_password:
    external: true
  db_root_user:
    external: true
```
B the way - the logging is really good and a great help for debugging! Really amazing container you made here =)

Ready to merge ;-)
