### ISSUE TITLE
InfluxDB 2 Backup fails on arm

### ISSUE THREAD

**Issue by martinfrancois** [tiredofit/docker-db-backup#319]
### Summary

When running a backup of an InfluxDB 2 container on a machine with arm64 / aarch64 architecture, it fails.

### Steps to reproduce

1. Prepare `docker-compose.yml` with an influxDB 2 container and `db-backup` (see below) on a server with arm architecture
2. Run `docker-compose up -d`
3. Look at the logs of `db-backup`
4. Backup failed

### What is the expected *correct* behavior?

Backups run through successfully.

### Relevant logs and/or screenshots

```
2024-01-01.15:15:57 [NOTICE] ** [01-influxdb__all] Dumping Influx2 database: 'all'
sudo: influx: command not found
2024-01-01.15:15:57 [ERROR] ** [01-influxdb__all] DB Backup of 'influx2_all_influxdb_20240101-151557' reported errors
2024-01-01.15:15:57 [ERROR] ** [01-influxdb__all] Skipping creating archive file because backup did not complete successfully
2024-01-01.15:15:57 [ERROR] ** [01-influxdb__all] Skipping Checksum creation because backup did not complete successfully
2024-01-01.15:15:57 [ERROR] ** [01-influxdb__all] Skipping moving DB Backup to final location because backup did not complete successfully
2024-01-01.15:15:57 [ERROR] ** [01-influxdb__all] Moving of backup 'influx2_all_influxdb_20240101-151557.xz' reported errors
2024-01-01.15:15:57 [NOTICE] ** [01-influxdb__all] DB Backup for 'all' time taken: Hours: 0 Minutes: 00 Seconds: 00
2024-01-01.15:15:57 [ERROR] ** [01-influxdb__all] Skipping Cleaning up old backups because there were errors in backing up
2024-01-01.15:15:57 [INFO] ** [01-influxdb__all] Backup 01 routines finish time: 2024-01-01 15:15:57 CET with exit code 0
2024-01-01.15:15:57 [NOTICE] ** [01-influxdb__all] Backup 01 routines time taken: Hours: 0 Minutes: 00 Seconds: 02
2024-01-01.15:15:57 [NOTICE] ** [01-influxdb__all] Sleeping for another 86398 seconds. Waking up at 2024-01-02 15:15:55 CET
```

### Environment

- Image version / tag: 4.0.33 
- Host OS: Ubuntu 22.04 LTS

`docker-compose.yml`:
```yaml
  db-backup:
    container_name: db-backup
    restart: unless-stopped
    image: tiredofit/db-backup:4.0.33
    volumes:
      - ./backups:/backup
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      - "CONTAINER_NAME=db-backup"
      - "CONTAINER_ENABLE_MONITORING=FALSE"

      - "BACKUP_JOB_CONCURRENCY=1"      # Only run one job at a time
      - "DEFAULT_CHECKSUM=SHA1"
      - "DEFAULT_COMPRESSION=XZ"
      - "DEFAULT_DUMP_INTERVAL=1440"    # Backup every day
      - "DEFAULT_DUMP_BEGIN=0000"       # Start backing up at midnight
      - "DEFAULT_CLEANUP_TIME=260640"   # Cleanup backups after 181 days
      - "DEFAULT_COMPRESSION_LEVEL=9"   # Compress at the highest level

      - "DB01_TYPE=influx"
      - "DB01_DUMP_INTERVAL=10080"
      - "DB01_PORT=${INFLUXDB_PORT}"
      - "DB01_INFLUX_VERSION=2"
      - "DB01_HOST=${INFLUXDB_HOST}"
      - "DB01_NAME=all"
      - "DB01_USER=${INFLUXDB_ORG}"
      - "DB01_PASS=${INFLUXDB_ADMIN_TOKEN}"
      - "DB01_BACKUP_LOCATION=FILESYSTEM"
```

</details>

    
### Possible fixes

Since the log said `sudo: influx: command not found` and when I enter the container and try to run `influx` it says it doesn't exist, it seems to me like it doesn't install the `influx` executable on arm systems.
