### ISSUE TITLE
Running as non root user

### ISSUE THREAD

**Issue by AnderssonPeter** [tiredofit/docker-db-backup#331]
Hi I'm trying to lock down my containers as much as I can and that entails running them as a non root user.

When I add
```yaml
user: 10002:10002
security_opt:
  - no-new-privileges:true
```

The container fails to start with the following:
```
s6-overlay-suexec: warning: unable to gain root privileges (is the suid bit set?)
s6-mkdir: warning: unable to mkdir /run/s6: Permission denied
s6-mkdir: warning: unable to mkdir /run/service: Permission denied
s6-overlay-suexec: fatal: child failed with exit code 111
```

Is there someway to run it as a non root user?
