### ISSUE TITLE
CouchDB Host 'couchdb' is not accessible, retrying

### ISSUE THREAD

**Issue by poudenes** [tiredofit/docker-db-backup#390]
Hi All,

Its impossible to backup couchDB
Can someone tell me what I do wrong?

Other 2 work perfect

CouchDB is accessible from the webgui.
Also working with Obsidian on my iMac

      
```
                                                                       ,---.
,--------.,--.                 ,--.            ,---.    ,--. ,--------.|   |
'--.  .--'`--',--.--. ,---.  ,-|  |     ,---. /  .-'    |  | '--.  .--'|  .'
   |  |   ,--.|  .--'| .-. :' .-. |    | .-. ||  `-,    |  |    |  |   |  |
   |  |   |  ||  |   \   --.\ `-' |    ' '-' '|  .-'    |  |.--.|  |   `--'
   `--'   `--'`--'    `----' `---'      `---' `--'      `--''--'`--'   .--.
                                                                       '--'
Image:  tiredofit/db-backup | Version  4.1.9 Type 'image_changelog' for details
Repository/Documentation: https://github.com/tiredofit/docker-db-backup/
License: MIT | © 2024 Dave Conroy
If this image provides you value  - Consider sponsoring my work for continued 
development, timely updates, and feature requests. Commercial support available.
                    More Info:  https://www.tiredofit.ca
2024-12-10.18:00:57 [NOTICE] ** [scheduling] Container configured for scheduled tasks with 'cron'
2024-12-10.18:00:58 [NOTICE] ** [messaging] Container configured to route mail via SMTP to 'postfix-relay'
2024-12-10.18:01:01 [STARTING] ** [scheduling] [1] Starting cron
2024-12-10.18:01:02 [INFO] ** [01-postgres__ALL] Next Backup at 2024-12-11 13:05:00 CET
2024-12-10.18:01:04 [INFO] ** [02-192.168.100.24__ALL] Next Backup at 2024-12-11 13:10:00 CET
2024-12-10.18:01:05 [INFO] ** [03-couchdb__ALL] Next Backup at 2024-12-10 18:01:05 CET
2024-12-10.18:01:11 [WARN] ** [03-couchdb__ALL] CouchDB Host 'couchdb' is not accessible, retrying.. (5 seconds so far)
2024-12-10.18:01:16 [WARN] ** [03-couchdb__ALL] CouchDB Host 'couchdb' is not accessible, retrying.. (10 seconds so far)
2024-12-10.18:01:21 [WARN] ** [03-couchdb__ALL] CouchDB Host 'couchdb' is not accessible, retrying.. (15 seconds so far)
2024-12-10.18:01:26 [WARN] ** [03-couchdb__ALL] CouchDB Host 'couchdb' is not accessible, retrying.. (20 seconds so far)
```

```
version: "3.9"
services:

  db-backup:
    image: tiredofit/db-backup
    container_name: db-backup
    hostname: db-backup
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/backup/databases:/backup
    environment:
      TZ: Europe/Amsterdam
      PUID: 1026
      PGID: 100
      CONTAINER_ENABLE_MONITORING: FALSE

      BACKUP_JOB_CONCURRENCY: 1     # Only run one job at a time
      DEFAULT_CHECKSUM: NONE        # Don't create checksums
      DEFAULT_COMPRESSION: ZSTD     # Compress all with ZSTD
      DEFAULT_DUMP_INTERVAL: 1440   # Backup every 1440 minutes
      DEFAULT_DUMP_BEGIN: 0000      # Start backing up at midnight
      DEFAULT_CLEANUP_TIME: 8640    # Cleanup backups after a week
      DEFAULT_FILESYSTEM_ARCHIVE_PATH: "/backup/archive/"
      DEFAULT_ARCHIVE_TIME: 1440

      DB01_TYPE: pgsql
      DB01_HOST: postgres
      DB01_NAME: ALL
      DB01_USER: SECRET
      DB01_PASS: SECRET
      DB01_BACKUP_INTERVAL: 1440
      DB01_BACKUP_BEGIN: 1305
      DB01_CLEANUP_TIME: 8640
      DB01_CHECKSUM: MD5
      DB01_COMPRESSION: GZ
      DB01_ARCHIVE_TIME: 1
      
      DB02_TYPE: mysql
      DB02_HOST: 192.168.100.24
      DB02_NAME: ALL
      DB02_USER: SECRET
      DB02_PASS: SECRET
      DB02_BACKUP_INTERVAL: 1440
      DB02_BACKUP_BEGIN: 1310
      DB02_CLEANUP_TIME: 8640
      DB02_CHECKSUM: MD5
      DB02_COMPRESSION: GZ
      DB02_ARCHIVE_TIME: 1

      DB03_TYPE: couch
      DB03_HOST: couchdb
      DB03_NAME: ALL
      DB03_USER: SECRET
      DB03_PASS: SECRET
      DB03_PORT: 5984

    networks:
       synology:
         ipv4_address: 172.30.33.100

networks:
  synology:
    external: true
```
