### ISSUE TITLE
Can't access Database after update

### ISSUE THREAD

**Issue by bf8392** [tiredofit/docker-db-backup#49]
Hi :-) I recently made an update to your latest container, and since then I get:
```
Database not accessible - retrieving
```
Are docker-secrets still supported? I'm running in swarm...

**Comment by tiredofit** [comment]
Secrets still should be supported! 
Whats your DB_TYPE ?

**Comment by bd8392** [comment]
Mariadb

**Comment by tiredofit** [comment]
Interesting, We haven't touched that in a while.
Could you send me some full container logs privately to my email?

Preferably DEBUG_MODE=TRUE - Note, you'll want to hide your host and password as that will expose it.

**Comment by bd8392** [comment]
I think there is a typo in the mysql command...there is no space after password...also user seems not to be picked up...If you spot some private Info please inform me, but I think I filtered everything out =)

```
q8soi  [44m[WARN][49m /etc/services.available/10-db-backup/run ** [db-backup] MySQL/MariaDB Server 'mariadb' is not accessible, retrying.. (45 seconds so far)
q8soi  + sleep 5
q8soi  + ((  COUNTER+=5  ))
q8soi  + true
q8soi  + mysqlcmd='mysql -u -P 3306 -h mariadb -pSomepass'
q8soi  ++ mysql -u -P 3306 -h mariadb '-pSomepass' -e 'SELECT COUNT(*) FROM information_schema.FILES;'
q8soi  + out='ERROR 1045 (28000): Access denied for user '\''-P'\''@'\''33.6.3.9'\'' (using password: YES)'
q8soi  + echo 'ERROR 1045 (28000): Access denied for user '\''-P'\''@'\''33.6.3.9'\'' (using password: YES)'
q8soi  + grep -E 'COUNT|Enter'
q8soi  + '[' 1 -eq 0 ']'
q8soi  + print_warn 'MySQL/MariaDB Server '\''mariadb'\'' is not accessible, retrying.. (50 seconds so far)'
q8soi  + output_off
q8soi  + '[' TRUE = TRUE ']'
q8soi  + set +x
```

**Comment by tiredofit** [comment]
No space is correct after the -p.

Are you sure you are on the most recent image? We stripped out that -p field a while back and started using a different way for password storage inside the image. You can try a tagged release `tiredofit/db-backup:2.3.0`

**Comment by bd8392** [comment]
Yes I justz checked...using taged tiredofit 2.3.0...Here is my config:
```
  tiredofit-db-backup:
    image: tiredofit/db-backup:2.3.0
    environment:
      COMPRESSION: NONE
      DB_CLEANUP_TIME: '2880'
      DB_DUMP_FREQ: '1440'
      DB_HOST: mariadb
      DB_PASS_FILE: /database_password
      DB_PORT: '3306'
      DB_TYPE: mariadb
      DB_USER_FILE: /database_user
      DEBUG_MODE: 'TRUE'
      MD5: 'TRUE'
      SPLIT_DB: 'TRUE'
      TIMEZONE: Europe/Vienna
    volumes:
     - mariadb_backups:/backup
     - tiredofit_scripts:/assets/custom-scripts
    networks:
     - apprise_notifier_net
     - database_stack_net
    secrets:
     -
      source: mariadb_root_password
      target: /database_password
     -
      source: mariadb_root_user
      target: /database_user
    logging:
      driver: json-file
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
```
I can`t figure out qwhats wrong as everything is mounted as before...
