### ISSUE TITLE
How to backup all/multiple influxdb databases

### ISSUE THREAD

**Issue by modem7** [tiredofit/docker-db-backup#77]
### Summary

How to backup all influxdb databases?

### Steps to reproduce

```yaml
  db-backup2:
    container_name: GrafanaDBBackup
    image: tiredofit/db-backup
    volumes:
      - $USERDIR/DBBackup/Grafana:/backup
      - $USERDIR/DBBackup/scripts/post-script.sh:/assets/custom-scripts/post-script.sh
    environment:
      - TIMEZONE=$TZ
      - DB_TYPE=influx
      - DB_HOST=influxdb
      - DB_PORT=8086
      - DB_NAME=??? # (database names: "varken" and "telegraf")
      - DB_USER=rootusername
      - DB_PASS=rootpassword
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0300
      - DB_CLEANUP_TIME=1440
      - MD5=FALSE
      # - COMPRESSION=GZ
      - SPLIT_DB=TRUE
    networks:
      - isolated
    depends_on:
      - influxdb
    restart: always
```

If I leave DB_NAME empty or exclude it completely, it doesn't backup any DB's, but if I put in a single DB is backs it up as expected. 

I saw https://github.com/tiredofit/docker-db-backup/issues/51 but not quite sure how to implement multiple DB names in there
