### ISSUE TITLE
mysql backup does not work without password

### ISSUE THREAD

**Issue by sbrunecker** [tiredofit/docker-db-backup#80]
### Summary

Automatic backups for mysql do not work without password. Calling `backup-now` asks for a password input.

### Steps to reproduce

Sample docker-compose file:

```
version: '3.7'
services:
  mysql:
    image: mysql:8
    command: mysqld --skip-ssl
    environment:
      - MYSQL_USER=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=test
    container_name: db

  backup:
    image: tiredofit/db-backup:latest
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=test
      - DB_NAME=test
      - DB_DUMP_BEGIN=+1
    container_name: backup
```

### What is the expected *correct* behavior?

Database is backed up.

### Possible fixes

The culprit is: 
https://github.com/tiredofit/docker-db-backup/blob/c81d8e2713b1d58a41460eb0a712d451d050c20e/install/etc/services.available/10-db-backup/run#L296

This gets stuck waiting for a password input.

A little below there is an `export` for PostgreSQL. That would probably solve it:
https://github.com/tiredofit/docker-db-backup/blob/c81d8e2713b1d58a41460eb0a712d451d050c20e/install/etc/services.available/10-db-backup/run#L318

It was also already done before for mysql:
https://github.com/tiredofit/docker-db-backup/blob/c81d8e2713b1d58a41460eb0a712d451d050c20e/install/etc/services.available/10-db-backup/run#L124
