### ISSUE TITLE
Mariadb - 

### ISSUE THREAD

**Issue by samcro1967** [tiredofit/docker-db-backup#90]
### Summary

Unable to connect to and backup a mariadb instance.

### Steps to reproduce

Setup latest linuxserver/mariadb and tiredofit/db containers.
**docker-compose**
```
version: '3.8' 
services:
  mariadb:
      hostname: mariadb
      image: linuxserver/mariadb:latest
      container_name: mariadb
      restart: always
      ports:
       - "3306:3306"
      volumes:
       - "${docker}/mariadb:/config"
      environment:
       - TZ=America/Chicago
       - PUID=1000
       - PGID=1000
       - MYSQL_ROOT_PASSWORD=password
       - MYSQL_DATABASE=piwigo
       - MYSQL_USER=user
       - MYSQL_PASSWORD=password
      networks:
       - wg-pia
    mariadb-backup:
      hostname: mariadb-backup
      image: tiredofit/db-backup:latest
      container_name: mariadb-backup
      restart: always
      environment:
       - DB_TYPE=mysql
       - DB_HOST=mariadb
       - DB_PORT=3306
       - DB_USER=root
       - DB_PASS="password"
       - DB_DUMP_FREQ=1440
       - DB_DUMP_BEGIN=+0
       - DB_CLEANUP_TIME=8640
       - MD5=FALSE
       - COMPRESSION=GZ
       - SPLIT_DB=FALSE
      volumes:
       - "${docker}/mariadb-backup:/backup"
      networks:
       - wg-pia
      links:
       - mariadb
```

### What is the expected *correct* behavior?

Container is able to connect to the mariadb instance and perform a backup.

### Environment

- Image version / tag:  latest
- Host OS:  Ubuntu 20.04.3 LTS
- Docker:  20.10.11

**Logs**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 00-functions: applying...
[fix-attrs.d] 00-functions: exited 0.
[fix-attrs.d] 01-s6: applying...
[fix-attrs.d] 01-s6: exited 0.
[fix-attrs.d] 02-zabbix: applying...
[fix-attrs.d] 02-zabbix: exited 0.
[fix-attrs.d] 03-logrotate: applying...
[fix-attrs.d] 03-logrotate: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-startup: executing...
[cont-init.d] 00-startup: exited 0.
[cont-init.d] 01-timezone: executing...
[cont-init.d] 01-timezone: exited 0.
[cont-init.d] 02-permissions: executing...
[cont-init.d] 02-permissions: exited 0.
[cont-init.d] 03-monitoring: executing...
2021-12-09-12:33:38 [NOTICE] ** [monitoring] Container configured for monitoring with 'zabbix modern'
[cont-init.d] 03-monitoring: exited 0.
[cont-init.d] 04-scheduling: executing...
2021-12-09-12:33:39 [NOTICE] ** [scheduling] Container configured for scheduled tasks with 'cron'
[cont-init.d] 04-scheduling: exited 0.
[cont-init.d] 05-logging: executing...
2021-12-09-12:33:39 [NOTICE] ** [logging] Disabling Log Shipping Functionality
[cont-init.d] 05-logging: exited 0.
[cont-init.d] 06-messaging: executing...
2021-12-09-12:33:39 [NOTICE] ** [messaging] Disabling Container messaging features
[cont-init.d] 06-messaging: exited 0.
[cont-init.d] 10-db-backup: executing...
[cont-init.d] 10-db-backup: exited 0.
[cont-init.d] 99-container: executing...
[cont-init.d] 99-container: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2021-12-09-12:33:39 [STARTING] ** [monitoring] [1] Starting Zabbix Agent (modern) 5.4.8
2021-12-09-12:33:39 [STARTING] ** [scheduling] [1] Starting cron
date: invalid date '@'
2021-12-09-12:33:49 [NOTICE] ** [db-backup] Next Backup at
2021-12-09-12:33:49 [WARN] ** [db-backup] MySQL/MariaDB Server 'mariadb' is not accessible, retrying.. (0 seconds so far)
```

I am able to ping the mariadb instance from this container and the following command executes successfully.  I have another instance of this container running and it is able to successfully backup a postgres instance.
docker exec mariadb-backup sh -c "mysql -uroot -pHtpc_osuhickeys -P 3306 -h mariadb -e 'SELECT COUNT(*) FROM piwigo.piwigo_images;'"
COUNT(*)
1217
